### ISSUE TITLE
Lists of structs

### ISSUE THREAD

**Issue by cswinter** [capnproto/capnproto-rust#100]
I have a schema that has lists of structs and can't figure out how to serialize messages for it. There is `struct_list::Builder` but that doesn't seem to have a method to actually push elements and I haven't found examples of constructing lists of structs. Is there any way of doing this?

My schema is a superset of this:
```capnp
struct Column {
    codec @4 :List(CodecOp);
    data @5 :List(DataSection);
}

struct CodecOp {
    union {
        add @0 :Add;
        unpackStrings @6 :Void;
    }
}

struct DataSection {
    union {
        u8 @0 :List(UInt8);
        u16 @1 :List(UInt16);
    }
}
```

**Comment by dwrensha** [comment]
There is an example here: https://github.com/capnproto/capnproto-rust/blob/a614fa8a094e7c6e1596046a58c2cf1e2d62533a/example/addressbook/addressbook.rs#L36

You need to first set the length of the list with e.g. the `init_codec(n)` method. Then you can get each element and modify them.

If you don't know beforehand how long the list will be, you can accumulate the structs in a `std::vec::Vec` and then write them all at once to the `struct_list::Builder`.

**Comment by cswinter** [comment]
D'oh, the example was there all along. Thanks a bunch!

Also congrats, you are now responsible for the long term data storage format in [LocustDB](https://github.com/cswinter/LocustDB) :D
In case you want to link to the schema in your README.md, here's the full code:
- Schema: [src/storage_format.capnp](https://github.com/cswinter/LocustDB/blob/3596abf8e56650806553faac4bfecdbae73e3daa/src/storage_format.capnp)
- (De)serialization: [src/disk_store/rocksdb.rs#L102](https://github.com/cswinter/LocustDB/blob/3596abf8e56650806553faac4bfecdbae73e3daa/src/disk_store/rocksdb.rs#L102)

**Comment by dwrensha** [comment]
Cool! I'm glad that you are finding `capnproto-rust` to be useful.

Just a heads-up: I noticed your usage of `bytes_to_words()` here: https://github.com/cswinter/LocustDB/blob/3596abf8e56650806553faac4bfecdbae73e3daa/src/disk_store/rocksdb.rs#L104

In the next version of `capnproto-rust`, I'm marking that function unsafe: https://github.com/capnproto/capnproto-rust/blob/fb22963e14203424f94835f0dc47c12e877b5e4c/capnp/src/lib.rs#L117

I just opened this issue for discussion: https://github.com/capnproto/capnproto-rust/issues/101

**Comment by cswinter** [comment]
Oh good to know, thanks for making me aware of this!
