### ISSUE TITLE
reading from unaligned byte buffers

### ISSUE THREAD

**Issue by dwrensha** [capnproto/capnproto-rust#101]
It's common to want to call `serialize::read_message_from_words()` to read a message from a `&[u8]`. We provide a `bytes_to_words()` function to allow that:

https://github.com/capnproto/capnproto-rust/blob/fb22963e14203424f94835f0dc47c12e877b5e4c/capnp/src/lib.rs#L117

but there are possible alignment issues that can arise. The usual advice for such situations is to dynamically check whether your `&[u8]` is `Word`-aligned, and if it isn't you can copy the bytes into a buffer that is sufficiently aligned. Unfortunately, such copying is not free, and it can sometimes be tricky to determine exactly where the copied-to buffer should live. It would be significantly more convenient if `capnproto-rust` could just work with `&[u8]` values directly. To achieve this, many of the things in `layout.rs` that now use `transmute()` would become calls to ~the `byteorder` crate~ [standard library functions](https://doc.rust-lang.org/std/primitive.u64.html#method.from_le_bytes). Presumably that would come with a performance cost, but some preliminary measurements I've done suggest that it might not be so bad, and the resulting code would likely have much less `unsafe`, so it might be worth it.

**Comment by bfrog** [comment]
Yes, this would make using capnp much easier in a zero copy way with lmdb, which would be spectacular.

**Comment by tecywiz121** [comment]
Is there no way to get both performance and convenience? You've probably seen it, but the `aligned` crate seems to provide a wrapper around arrays that ensures alignment. Maybe expanding that and supporting it here, and in other crates would be a viable third option.

**Comment by dwrensha** [comment]
> the aligned crate seems to provide a wrapper around arrays that ensures alignment.

That crate does look useful, but I don't think it solves my particular problem here: if I have `x: &[u8]` that's not aligned, there's no way to force it to be aligned without copying the data.

**Comment by tecywiz121** [comment]
I think my suggestion would be to require an aligned buffer instead of a `&[u8]`.

Hopefully whatever source crates can support reading into a preallocated buffer, or be modified to return one directly?

**Comment by zserik** [comment]
Would it be possible to make the code (that needs to deal with this) generic about the fact if something is aligned or unaligned?

**Comment by tecywiz121** [comment]
Oh, that's a neat idea! If you implement a trait for both `&[u8]` and for the correct type from the `aligned` crate you could have convenience if you don't care, and performance if you do!

**Comment by zserik** [comment]
It would probably be a good idea to look at how the [`zerocopy`](https://crates.io/crates/zerocopy) crate works around this issue, too.
There are also many good suggestions in the comments under the [reddit post](https://www.reddit.com/r/rust/comments/en9fmn/should_capnprotorust_force_users_to_worry_about/).

**Comment by dwrensha** [comment]
This is done. See https://dwrensha.github.io/capnproto-rust/2020/01/19/new-feature-to-allow-unaligned-buffers.html
