### ISSUE TITLE
Name clashes: Include generated code inside of a module which contains the corresponding schema

### ISSUE THREAD

**Issue by mashedcode** [capnproto/capnproto-rust#107]
Currently the user is expected to include all generated code at project root.
```
// lib.rs
pub mod schema_capnp {
    include!(concat!(env!("OUT_DIR"), "/foo/schema_capnp.rs"));
}
```
He then may use that code inside of a module:
```
// foo/mod.rs
use ::schema_capnp::foo;
```
This may be inconvenient in some cases and not possible to do with the following structure:
```
lib.rs
> foo
>> mod.rs
>> schema.capnp
> bar
>> mod.rs
>> schema.capnp
```
Including both schema files in lib.rs is not possible due to name the obvious name clash.
Therefore one would like to include it directly in the corresponding `mod.rs` to avoid  the name clash.
**But** currently the generated code assumes that its code will be a module at root level and refers to itself with `::schema_capnp` in the example above.
This could be easily modified so that it assumes it's included in the same directory as the schema file is so the resulting handle would be `::foo::schema_capnp`.
_But_ that would make it impossible to include it in a different file other than `foo/mod.rs` (in the example above), which would break the existing behavior.

I don't have a good idea to solve this.

Personally I feel like forcing the user to include the module in the same directory as the schema file would be better than the current behavior. As it's more natural and name clashes would be impossible.

**Comment by mashedcode** [comment]
[A breaking change could look like this](https://github.com/mashedcode/capnproto-rust/commit/352f8070a4fb719d03052341814a89b0c30dc70a) but I hope that someone has got a better idea to solve this issue.

**Comment by dwrensha** [comment]
Thanks for the report. There has been some previous discussion this topic:
https://github.com/capnproto/capnproto-rust/issues/16
https://github.com/capnproto/capnpc-rust/issues/5 
https://github.com/capnproto/capnpc-rust/issues/30

**Comment by mashedcode** [comment]
Closing in favor of #16. I hope we'll get some progress done there.
