### ISSUE TITLE
How to serialize a struct with two lists?

### ISSUE THREAD

**Issue by pravic** [capnproto/capnproto-rust#116]
Such a silly question but I could not succeed in it.

```
struct Org {
  people @0 :List(Person);
  inventory @1 :List(Item);
  name @2 :Text;
}

struct Person {}
struct Item {}
```

```rust
let org = message.init_root::<org::Builder>();
let people = org.init_people(capacity);  //  <-- here `init_people` consumes the `org`
let items = org.init_inventory(capacity); // how to?
```

I saw a `set_people` method in the generated code, but no idea how to create an appropriate `people` instance in order to pass it there.

**Comment by pravic** [comment]
Indeed. I've tried that already, but the RLS has tricked me. But it does work.

Thanks!

**Comment by pravic** [comment]
And out of curiosity: is there a way to compose a list separately and pass it to the message later (that `set_people` method that I mentioned above, it takes a reference to a `Reader`)?

Something like

```rust

let list = unimplemented!(); // <--
// fill the `list`

let org = message.init_root::<org::Builder>();
org.set_people(list.as_reader()); // <--
```

**Comment by dwrensha** [comment]
You need some message in which to allocate the elements of the list. capnproto-c++ has an ["orphan" interface](https://capnproto.org/cxx.html#orphans) that helps in the case where you want to allocate in a single message and then rearrange some pointers. capnproto-rust does not have that (yet).

You could do:
```rust
let mut tmp_message = capnp::message::Builder::new_default();
let mut list: capnp::struct_list<Person::Owned> = message.init_root();
// fill the `list`

let org = message.init_root::<org::Builder>();
org.set_people(list.as_reader()); // <--
```

**Comment by pravic** [comment]
That exactly it.
