### ISSUE TITLE
Compile Error when trying to compile schema with a List in it

### ISSUE THREAD

**Issue by gibsond** [capnproto/capnproto-rust#122]
I have a schema as such:
```capnp
struct GatewayMsg {
       daqs @0 :List(DaqMsg);
       seq @1 :UInt64;
       title @2 :Text;
       version @3 :Text;
       datetime @4 :Text;
       health @5: UInt16;

       struct DaqMsg {
       	      mdata @0 :Data;
	}
}
```
And I get the error:
rror[E0433]: failed to resolve: could not find `foo_capnp` in `{{root}}`
   --> /home/gibsond/rust_projs/es1800_zmqsubr/target/debug/build/es1800_zmqsubr-fbe222f1c797ab23/out/foo_capnp.rs:326:80
    |
326 |     pub fn get_daqs(self) -> ::capnp::Result<::capnp::struct_list::Reader<'a,::foo_capnp::gateway_msg::daq_msg::Owned>> {
    |                                                                                ^^^^^^^^^ could not find `foo_capnp` in `{{root}}`

error[E0433]: failed to resolve: could not find `foo_capnp` in `{{root}}`
   --> /home/gibsond/rust_projs/es1800_zmqsubr/target/debug/build/es1800_zmqsubr-fbe222f1c797ab23/out/foo_capnp.rs:416:81
    |
416 |     pub fn get_daqs(self) -> ::capnp::Result<::capnp::struct_list::Builder<'a,::foo_capnp::gateway_msg::daq_msg::Owned>> {
    |                                                                                 ^^^^^^^^^ could not find `foo_capnp` in `{{root}}`

error[E0433]: failed to resolve: could not find `foo_capnp` in `{{root}}`
   --> /home/gibsond/rust_projs/es1800_zmqsubr/target/debug/build/es1800_zmqsubr-fbe222f1c797ab23/out/foo_capnp.rs:420:73
    |
420 |     pub fn set_daqs(&mut self, value: ::capnp::struct_list::Reader<'a,::foo_capnp::gateway_msg::daq_msg::Owned>) -> ::capnp::Result<()> {
    |                                                                         ^^^^^^^^^ could not find `foo_capnp` in `{{root}}`

error[E0433]: failed to resolve: could not find `foo_capnp` in `{{root}}`
   --> /home/gibsond/rust_projs/es1800_zmqsubr/target/debug/build/es1800_zmqsubr-fbe222f1c797ab23/out/foo_capnp.rs:424:77
    |
424 |     pub fn init_daqs(self, size: u32) -> ::capnp::struct_list::Builder<'a,::foo_capnp::gateway_msg::daq_msg::Owned> {
    |                                                                             ^^^^^^^^^ could not find `foo_capnp` in `{{root}}`

I can fix the problem, after the fact, by changing the generated source code:
::foo_capnp::first_msg::second_msg to self::second_msg.

Or, in this example
:foo_capnp::gateway_msg::daq_msg to self::daq_msg

I see a similar issue inf the closed issues:
capnproto/capnpc-rust#5
capnproto/capnpc-rust#30
capnproto-rust/issues/16

However, this issue comes up in capnp version 0.9.4, and capnpc version 0.9.3.

Any help would be appreciated,
Daniel Gibson

**Comment by dwrensha** [comment]
Are you using `edition = "2018"` in your `Cargo.toml`? If you, you'll need to call [`edition(RustEdition::Rust2018)` ](https://github.com/capnproto/capnproto-rust/blob/95c149fd614edf8260bf29f6d10d44c641e76e88/capnpc/src/lib.rs#L158) when constructing your `CompilerCommand` in your `build.rs`.

**Comment by gibsond** [comment]
Awesome !! Thank-you, that fixed the problem.  Any thought of having capnproto-rust read the edition from the Cargo.toml file?

**Comment by dwrensha** [comment]
I don't there's currently any way to automatically detect the edition.

I found some discussion on this topic:
https://github.com/rust-lang/cargo/issues/6408
https://users.rust-lang.org/t/detect-edition-2018-from-cargo-build-rs/21134/5
