### ISSUE TITLE
Is there a way to specify the message traversal limit for an RPC request?

### ISSUE THREAD

**Issue by pdiffley** [capnproto/capnproto-rust#124]
I am sending an RPC request that exceeds the default message traversal limit. I know that if I am reading a message with capnp::serialize::read_message, I can provide a ReaderOptions struct to change the traversal limit, but I cannot find this option for RPC requests. It is possible to send RPCs that are larger than the default traversal limit?

**Comment by dwrensha** [comment]
Yes. You provide the `ReaderOptions` when you construct the `twoparty::VatNetwork`: https://github.com/capnproto/capnproto-rust/blob/9a4a3d1f337a03d44d39298878243cc51d11759d/capnp-rpc/src/twoparty.rs#L193

e.g. in this example, the `ReaderOptions` is the default: https://github.com/capnproto/capnproto-rust/blob/9a4a3d1f337a03d44d39298878243cc51d11759d/capnp-rpc/examples/calculator/client.rs#L71

**Comment by pdiffley** [comment]
That did it. Thanks!
