### ISSUE TITLE
Implementing default values for pointer fields

### ISSUE THREAD

**Issue by rytone** [capnproto/capnproto-rust#127]
Right now, pointer fields (structs, lists, etc.) cannot have default values ([codegen.rs](https://github.com/capnproto/capnproto-rust/blob/master/capnpc/src/codegen.rs#L444), capnproto/capnpc-rust#38), but I need this feature for a project I am working on. I am interested in implementing it into capnpc Rust generator myself, but I am pretty new to capnproto overall and don't really know where to start. It's mentioned in the old issue that it should be "fairly straightforward" to implement pointer defaults, so I'm curious about the overall logic for implementing it so I can give it a shot.

**Comment by dwrensha** [comment]
I started to look at this today. Here's what I have so far: https://github.com/capnproto/capnproto-rust/commit/ab04806adf7f89e5496692d52774ae777343fe85

I think the biggest remaining obstacle is porting the [`copyMessage()`](https://github.com/capnproto/capnproto/blob/d4d970037f018624b66394dee2582b2aca64317d/c%2B%2B/src/capnp/layout.c%2B%2B#L914) function from the C++ implementation.

**Comment by dwrensha** [comment]
Done in: https://github.com/capnproto/capnproto-rust/commit/f9ae25c977662b64b0724f465f34cacab8747b86
