### ISSUE TITLE
Cannot use `T` or `U` as type parameters?

### ISSUE THREAD

**Issue by tokahuke** [capnproto/capnproto-rust#132]
So, I have this interface:

```capnp
interface Function(T, U) {
  apply @0 (element :T) -> (value :U);
  # Maps one element to anothe element of possibly aonther kind.
}
```
When I generate the code with `capnpc`, I get the following errors from within the generated code:

```
error[E0403]: the name `U` is already used for a generic parameter in this list of generic parameters
    |
809 |   pub struct ToClient<U,T,U> where T: for<'c> ::capnp::traits::Owned<'c>, U: for<'c> ::capnp::traits::Owned<'c>  {
    |                       -   ^ already used
    |                       |
    |                       first use of `U`
```

Although this goes smoothly when I do

```capnp
interface Predicate(T) {
  predicate @0 (element :T) -> (value :Bool);
  # Asserts whether a certain element is or is not contained in a set.
}
```

I have been using `V` and `W` instead as a replacement and it works just fine. My version is `capnpc = "0.9.5"`

**Comment by dwrensha** [comment]
Thanks for the report! This is fixed in https://github.com/capnproto/capnproto-rust/commit/eddcc1ea8599be0ae62209509ae48e1e99ee00d8, which prepends an underscore to avoid such conflicts.
