### ISSUE TITLE
How to return a Reader

### ISSUE THREAD

**Issue by bfrog** [capnproto/capnproto-rust#139]
I'm looking to use capnproto with lmdb to get a zero-copy reader from the slice the lmdb crate returns on get() calls.

I'd like a function that looks like, using the addressbook type as an example, that does no memory
allocation whatsoever. Seems like rust's ownership should allow it intuitively, but maybe not.

``` rust
fn get_addressbook<'a>(tx: &'a lmdb::RoTransaction, key: u64) -> Result<addressbook::Reader> {
   let buf = tx.get(key)?;
   let mut buf_reader = BufReader::new(buf);
   let msg = capnp::serialize::read_message(&mut buf_reader, ReadOptions::new())?;
   let reader = msg.get_root::<addressbook::Reader>();
   return Ok(Reader)
}
```

Is there a good way of doing that with capnp in safe rust land? Stuffing everything in a struct with 'a as the lifetime didn't pan out like I guess I was hoping it would. Feels like I'd need to use something else to ensure the lifetime of the reader depends on msg, depends on buf_reader, which depends on buf, which at long last depends on the lifetime of the RoTransaction.

Thanks for the great crate!

**Comment by dwrensha** [comment]
The fundamental issue is that `capnp` wants data in a message to be aligned to an eight-byte boundary, and it looks like `lmdb` does not guarantee that alignment.

Something like this should work:
```rust
fn get_addressbook<'a>(tx: &'a lmdb::RoTransaction, key: u64)
  -> Result<capnp::message::TypedReader<capnp::serialize::SliceSegments<'a>,
                                        addressbook::Owned>>
{
   let buf = tx.get(key)?;
   Ok(capnp::serialize::read_message_from_words(
     unsafe { capnp::Word::bytes_to_words(buf) },
     ReadOptions::new()?).into_typed())

}
```

but note the caveats on `bytes_to_words()`: https://github.com/capnproto/capnproto-rust/blob/8b1998fc2559f767b1191f057012bb22920b350d/capnp/src/lib.rs#L87-L91

Here is an issue I've opened on this topic: https://github.com/capnproto/capnproto-rust/issues/101

**Comment by bfrog** [comment]
Thank you for the fast response!
