### ISSUE TITLE
Question: should Disconnector be part of capnp_rpc's exports?

### ISSUE THREAD

**Issue by ckoparkar** [capnproto/capnproto-rust#140]
I have a function `get_client` which returns a bootstrapped RPC client. I'd also like to return a `capnp_rpc::rpc::Disconnector`, so that the caller of `get_clinet` can run it when required. However, [`Disconnector`](https://github.com/capnproto/capnproto-rust/blob/master/capnp-rpc/src/rpc.rs#L1528) is not exported from the crate at the moment. Is this an oversight? Or am I using it wrong ?

**Comment by dwrensha** [comment]
Yeah, looks like we missed that when it was added in https://github.com/capnproto/capnp-rpc-rust/pull/24.
