### ISSUE TITLE
Implement a `OwnedSegments` constructor

### ISSUE THREAD

**Issue by eliaslevy** [capnproto/capnproto-rust#144]
Users of the crate cannot create their own `OwnedSegments` as there is no constructor and the struct fields are private.  A constructor would be useful to take a slice of segments (`&[&[Word]]`) and convert them to `OwnedSegments` to take ownership and to use with a `Reader`.

**Comment by dwrensha** [comment]
> Users of the crate cannot create their own OwnedSegments as there is no constructor and the struct fields are private. 

The `ReaderSegments` trait exists for this purpose:
https://github.com/capnproto/capnproto-rust/blob/96f2f7894fbbf55e741c39b183a824e27ddbcc3e/capnp/src/message.rs#L90

For example, the `capnp-futures` crate defines its own `OwnedSegments` and implements that trait: https://github.com/capnproto/capnproto-rust/blob/96f2f7894fbbf55e741c39b183a824e27ddbcc3e/capnp-futures/src/serialize.rs#L34

Does `ReaderSegments` work for you?

If I remember correctly, the main reason I haven't exposed the internals of `OwnedSegments` is that I wanted to keep the door open for possible optimizations, like maybe if there's only one segment we could avoid heap allocations.

----

> A constructor would be useful to take a slice of segments (&[&[Word]]) and convert them to OwnedSegments to take ownership and to use with a Reader.

Note that such a constructor would need to copy all of the segment into memory owned by the `OwnedSegments`. That could be rather expensive, so a new constructor like this does not seem like something that would be heavily used.

Can you describe your use can more deeply? Perhaps there is a better way to accomplish your goal.

**Comment by eliaslevy** [comment]
Of course, `Reader` takes a `ReaderSegments` trait.  Sorry for the noise.
