### ISSUE TITLE
Hung server connection with tokio-rustls

### ISSUE THREAD

**Issue by haata** [capnproto/capnproto-rust#147]
I've been working on pycapnp (client) <-(TLS)-> capnproto-rust (server), which is basically working now except for (what I hope) is the final hurdle.

There was some sort of write IO change in tokio-rustls-0.9.1 -> tokio-rustls-0.9.2 that seems to block all capnproto wait requests after the first exchange (amusingly if I request a bunch of promises before waiting I can actually get all of them, but then next time I make a request it also hangs).

Here are 3 examples, the first one works, the 2nd one is the first version not working, the 3rd one is the latest version,
https://github.com/haata/capntls/tree/tokio-rustls-0.9.1
```bash
cargo run server localhost:12345 &
cargo run client localhost:12345
    Finished dev [unoptimized + debuginfo] target(s) in 0.24s
     Running `target/debug/capntls client 'localhost:12345'`
tester@testserver.com:hello
tester@testserver.com:helloa
```
vs.
https://github.com/haata/capntls/tree/tokio-rustls-0.9.2
```bash
cargo run server localhost:12345 &
cargo run client localhost:12345
    Finished dev [unoptimized + debuginfo] target(s) in 0.15s
     Running `target/debug/capntls client 'localhost:12345'`
tester@testserver.com:hello
^C
```
and
https://github.com/haata/capntls/tree/tokio-rustls-0.10.1
```bash
cargo run server localhost:12345 &
cargo run client localhost:12345
    Finished dev [unoptimized + debuginfo] target(s) in 0.08s
     Running `target/debug/capntls client 'localhost:12345'`
tester@testserver.com:hello
^C
```

The suggested "fix" from the tokio-rustls side is detailed here: https://github.com/quininer/tokio-rustls/issues/37 unfortunately I'm not really sure how this change would fit into capnproto-rust (maybe somewhere in capnproto-futures?).

Anyways, I don't mind working on a patch though I might need some guidance on where to look.

**Comment by dwrensha** [comment]
The "suggested fix" seems to be "call `flush()`", and `capnp-futures` is already doing that:
https://github.com/capnproto/capnproto-rust/blob/96f2f7894fbbf55e741c39b183a824e27ddbcc3e/capnp-futures/src/serialize.rs#L413

So, at first glance, this looks to me like a bug somewhere other than capnproto-rust.

**Comment by haata** [comment]
Thanks for pointing this out!

Hmmm, I'll have keep hunting.

I traced the hung transaction to that particular commit in tokio-rustls so something is amiss around writing of data.

I haven't finished tracing all the way, but it seems like the server stop here:
https://github.com/capnproto/capnproto-rust/blob/master/capnp-futures/src/write_queue.rs#L196

**Comment by haata** [comment]
Turns out the issue was in tokio-rustls, https://github.com/quininer/tokio-rustls/commit/fe8fafecee85191efb73aa7edaed7021a5c8beff

Thanks for your help @dwrensha
