### ISSUE TITLE
Rust Vec<u8> in Capnproto

### ISSUE THREAD

**Issue by ogonbat** [capnproto/capnproto-rust#155]
Hi All

I need to move a Vec<u8> with Capnproto-rpc.
In my capnproto file i have used a List:

`

     interface Node {

        getCsr @0 () -> (csrresponse :CsrResponse);
        register @1 (certrequest: CertRequest);
        install @2 () -> ();

        struct CsrResponse {
            csr @0: List(UInt8);
        }
        struct CertRequest {
            cert @0: List(UInt8);
            caCert @1: List(UInt8);
        }
    }`

But when i have to use the cosde generated into the Server RPC, for example, I have no idea how to translate the Vec<u8> to a List and viceversa

thanks in advance for your help

**Comment by dwrensha** [comment]
You may want to consider using the [`Data` type](https://capnproto.org/language.html#built-in-types), which has the advantage of being guaranteed to be stored as contiguous bytes. (`List(UInt8)` may be encoded with padding bytes in certain situations.)

To translate a `Vec<u8>` into a `capnp::data::Builder`, you would first set the size of the builder with, for example, `init_csr(size)`. Then you could copy the bytes over with [`copy_from_slice()`](https://doc.rust-lang.org/std/primitive.slice.html#method.copy_from_slice).

Note that `capnp::data::Builder` is in fact just a type alias for `&mut[u8]`. To construct a `Vec<u8>` from one, you should be able to call [`into_vec()`](https://doc.rust-lang.org/std/primitive.slice.html#method.into_vec).
