### ISSUE TITLE
Open Port Safety

### ISSUE THREAD

**Issue by bfrog** [capnproto/capnproto-rust#156]
As I'm looking to create a new service, one where HTTP isn't a sensible or viable option, capnp comes right to mind. I'm wondering if cap'n'proto especially with rust as an RPC server has been left open to the world before and if there are things in place in the library and generated code to deal with such things.

Right off the bat I did see that there's the straightforward possibility of using tls to make the connection secure. Beyond that though I have some concerns...

Are invalid/garbage messages dealt with safely?
Are intentionally slow to send clients dealt with safely (slowloris like situations I believe)?

Generally are there ways of dealing with intentionally or unintentionally misbehaving clients which the internet is bound to unleash on any open port?

**Comment by dwrensha** [comment]
> Are invalid/garbage messages dealt with safely?

When capnp-rpc receives an invalid message, it will close the connection with an [`abort`](https://github.com/capnproto/capnproto/blob/eceea1640cb2d7fd537cc6aa36b51892e7f32134/c%2B%2B/src/capnp/rpc.capnp#L234) message. You have some control over what "invalid" means through the [`ReaderOptions` you pass to `VatNetwork::new()`](https://github.com/capnproto/capnproto-rust/blob/2f770dff7dab33dc7817fda7c5d647ea9168ea11/capnp-rpc/src/twoparty.rs#L192). Out-of-bounds pointers or type mismatches will always be considered invalid.

Not that there may still be bugs, and the base `capnp` crate does use `unsafe` code. I have done some fuzz testing, but it's hard to be 100% sure that there are not safety bugs.

> Are intentionally slow to send clients dealt with safely (slowloris like situations I believe)?

Slow clients won't slow down other clients, other than by consuming RAM and file descriptors. There's no built-in logic for automatically closing connections that aren't doing anything. Probably you could add that kind of logic by wrapping the `AsyncRead` and `AsyncWrite` objects that you pass to `capnp-rpc`.

**Comment by bfrog** [comment]
I really appreciate the answer, thanks again for the fantastic library!
