### ISSUE TITLE
Incorrect behavior of iterator methods

### ISSUE THREAD

**Issue by busimus** [capnproto/capnproto-rust#159]
I noticed that the `skip` method of the list reader iterator wasn't working as expected.

[Here's the code](https://gist.github.com/busimus/f24aca9791dc2585c4eea5e9d70a4a79) to reproduce the issue.
[Here's the code](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=c989cf778da73a8d43f24287c3100bfb) that I use as the reference of correct behavior. It uses an array of 6 integers, calls `.skip(2).skip(1)` on its iterator, and iterates over the remaining 3 items: 4, 5, 6.

The similar iteration code but with `capnp::struct_list::Reader` has different behavior:
1. After skipping, the first two iterations return the same item. 
2. If you call skip multiple times it doesn't add up the "offset" but overwrites it, so `.skip(2).skip(1)` only skips the first item.

So instead we get iteration over items 2, 2, 3, 4, 5, 6.

**Comment by dwrensha** [comment]
Thanks! This should be fixed by f9918e7e1c82678a54215ad103f148f4913a4e6e.
