### ISSUE TITLE
Cannot put .capnp file in a submodule

### ISSUE THREAD

**Issue by erickt** [capnproto/capnproto-rust#16]
(oops, accidentally submitted early)

Here's an example:

test.rs:

``` rust
extern crate capnp;

pub mod submod {
    #[path = "../test_capnp.rs"]
    pub mod test_capnp;
}

fn main() { }
```

test.capnp:

```
@0xb05abd72309922f1;

struct Test {
  test @0 :Int64;

  method @1 :Method;
  enum Method {
    unkown @0;
  }
}
```

This errors with:

```
test_capnp.rs:36:40: 36:50 error: failed to resolve. Maybe a missing `extern crate test_capnp`?
test_capnp.rs:36     pub fn get_method(&self) -> Option<::test_capnp::test::method::Reader> {
                                                        ^~~~~~~~~~
test_capnp.rs:36:40: 36:74 error: use of undeclared type name `test_capnp::test::method::Reader`
test_capnp.rs:36     pub fn get_method(&self) -> Option<::test_capnp::test::method::Reader> {
                                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
test_capnp.rs:64:40: 64:50 error: failed to resolve. Maybe a missing `extern crate test_capnp`?
test_capnp.rs:64     pub fn get_method(&self) -> Option<::test_capnp::test::method::Reader> {
                                                        ^~~~~~~~~~
test_capnp.rs:64:40: 64:74 error: use of undeclared type name `test_capnp::test::method::Reader`
test_capnp.rs:64     pub fn get_method(&self) -> Option<::test_capnp::test::method::Reader> {
                                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
test_capnp.rs:68:38: 68:48 error: failed to resolve. Maybe a missing `extern crate test_capnp`?
test_capnp.rs:68     pub fn set_method(&self, value : ::test_capnp::test::method::Reader) {
                                                      ^~~~~~~~~~
test_capnp.rs:68:38: 68:72 error: use of undeclared type name `test_capnp::test::method::Reader`
test_capnp.rs:68     pub fn set_method(&self, value : ::test_capnp::test::method::Reader) {
                                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
error: aborting due to 6 previous errors
```

The problem is that `test_capnp.rs` is using `::` to try to get to the top of the file, but instead that is referring to the top of the crate. Unfortunately I don't think there's any shorthand to get to the top of the local file scope, so to do this, we would need to create a series of `super::...`s to walk up the current module chain to get to the root.

**Comment by dwrensha** [comment]
This is mainly a code generation issue, so I'm closing in favor of this issue in capnpc-rust: https://github.com/dwrensha/capnpc-rust/issues/5

**Comment by dwrensha** [comment]
Reopening here, as capnpc-rust has been moved back into this repo.

**Comment by gibsond** [comment]
I am having a problem with this now.  In trying to see what the solution is, my search led me to capnproto/capnpc-rust#5 first, than this one, and from here capnproto/capnpc-rust#30.

It seems that #5 was closed because #16 was open, and #16 was closed because of #5.  Glad it has been re-opened as of August 30, 2018.

I can get mine to complie if I change the generated code with instances of, for example,  ::foo_capnp::first_msg::second_msg to self::second_msg.

This is using edition =  "2018" in the toml file.

I hope we can find a fix for this situation of using capnp List.

Thanks.

**Comment by olanod** [comment]
I'm also doing the replace hack `::{file}_capnp::{msg}::{sub_msg}` -> `self::{sub_msg}`. What would take to use `self`, `super`, `crate` and favor relative paths instead of absolute ones?

**Comment by dwrensha** [comment]
Fixed in 57ab3464f75a19c0386566f38b41be3bfb34962d.

**Comment by dwrensha** [comment]
To use the new feature, you need to import [`rust.capnp`](https://github.com/capnproto/capnproto-rust/blob/0b274109ce3c2855b6590cd80422465d69e48db1/capnpc/rust.capnp). Probably the easiest way to do that is to copy it and include it among your own schema files.

To indicate that you will include the generated code under the module `foo::bar::baz`, you would 
add a a file-level annotation `$Rust.parentModule("foo::bar::baz")`.

**Comment by gibsond** [comment]
Thank-you!
