### ISSUE TITLE
Schema inspection

### ISSUE THREAD

**Issue by eliaslevy** [capnproto/capnproto-rust#161]
Correct me if I am wrong, but currently there is no facility for schema inspection.  Note that I am not asking for dynamic parsing of data encoded in arbitrary schemas.  I am interested only in inspecting a schema (e.g. asking if a field exist and its type).

It seems like the compiler plug in handles binary representations of the schema, but the functionality is not made more widely available.

**Comment by dwrensha** [comment]
You are correct. Such a thing does not yet exist in capnproto-rust. One thing that it could useful for is implementing `Display` for capnp values in a way that does not involve generating extra code for each type.

**Comment by dwrensha** [comment]
Update: capnproto-rust now has reflection: https://dwrensha.github.io/capnproto-rust/2023/05/08/run-time-reflection.html

If you call `Introspect::introspect()` on a struct type, you will get a `StructSchema` object that lets you inspect information like field types and annotations.
