### ISSUE TITLE
Feature request: Annotations to rename symbols

### ISSUE THREAD

**Issue by kentonv** [capnproto/capnproto-rust#162]
We have a case where a schema originating from a C++ project cannot compile in Rust without modification, because it does something like this:

    struct Foo {
      union {
        bar @0 :Bool;
        pipeline @1 :SomeStruct;
        baz @2 :Text;
      }
    }

It turns out that the union member named `pipeline` results in the generation of a symbol with the capitalized name `Pipeline` in the generated Rust code, which conflicts with the nested `Pipeline` struct used for promise pipelining. Unfortunately, renaming the field now would break other projects that already use this schema.

The C++ code generator solves this class of problems by offering annotations which can be used to rename a field specifically for C++ purposes, e.g.:

    using Cxx = import "/capnp/c++.capnp";

    const delete :Text $Cxx.name("delete_") = "delete";

It looks like capnproto-rust currently does not define any annotations? Could it?

**Comment by dwrensha** [comment]
Done in 467edea327655063df9e9162594a0f007ffe6b9a.

**Comment by kentonv** [comment]
Nice! Thanks!
