### ISSUE TITLE
Building capnp-rpc requires capnpc in PATH

### ISSUE THREAD

**Issue by kabergstrom** [capnproto/capnproto-rust#163]
Currently, capnp-rpc has a `build.rs` file which uses capnpc's CompilerCommand to generate Rust code. The build.rs file will be run every time a user compiles capnp-rpc, even if capnp-rpc is a transitive dependency to the crate the user wants to compile. Since the schemas don't change after release, it would be great if the generated schemas could be committed to the repo and the generation run by the developer only when required to avoid users needing capnpc in their PATH.

**Comment by dwrensha** [comment]
Good idea! Done in ab6ecd26316855a737741a203a06fdd462d9e589.
