### ISSUE TITLE
Help, Load balance !!! How to keep (or reuse) the client in a lib

### ISSUE THREAD

**Issue by Tonyce** [capnproto/capnproto-rust#164]
I'm developing capnp client with Rust, and I want reuse the connetions that has been conneted. I tried to reuse the tcpStream , but got "questionId is already in use". so how can i hold the client for next use. is there some demo that i can learn something with.

**Comment by dwrensha** [comment]
I'm sorry, I don't fully understand what you're trying to do. Could you elaborate about what you mean by "reuse the connections"? Some code would be helpful.

**Comment by Tonyce** [comment]
what I mean is that how can i use load balance in rpc client，or some tips to use the tcp connect between one client with some servers in the balance way
