### ISSUE TITLE
How do I impliment my server?

### ISSUE THREAD

**Issue by procyclinsur** [capnproto/capnproto-rust#166]
I am very new to capnproto, and I do not see any other place to ask for help.

I have been struggling for 2-3 days to get my server impl built just to the point where I can test it.. (i.e. print the data to terminal)

Here is the capnp file:

```capnp
@0xeb1bbbd418f18514;

interface Job {
	new @0 (req :Request) -> (result :Result);
	struct Request {
		# Query parameters to be requested
		parms @0 :List(Text);
		# Source of the data dir://xxx s3://my-bucket/xx
		source @1 :Text;
	}
	struct Result {
		# Link to result file://xxx.csv s3://mybucket/xxx.csv
		# Or error if applicable
		union {
			link @0 :Text;
			error @1 :Text;
		}
	}
}
```

And the code I would like to implement:

```rust
use crate::rpc_capnp::{job};
use crate::rpc_capnp::job::{request,result};

struct Job;

impl job::Server for Job {
    fn new(&mut self, params: job::NewParams, mut results: job::NewResults)
    -> Promise<(), capnp::Error> {
        let request_reader = pry!(pry!(params.get()).get_req());
        let parms = request_reader.get_parms().unwrap();
        let source = request_reader.get_source().unwrap();
        println!("Parameters:");
        for item in parms.iter() {
            println!("{:?}", item);
        }
        println!("DataSource:");
        println!("{:?}", source);
        // something to return a reader for result???
        let rtn_val = ?????????;
        results.get().set_result(rtn_val);
        Promise::ok(())
    }
}
```

Do I need to construct a `result::Builder`? How might I go about that?  Any help would make me a very happy camper!

**Comment by dwrensha** [comment]
`results.get().init_result()` should give you a `result::Builder`. Then you just need to write your results to it in place, e.g. something like `results.get().init_result().set_link("foo");`.

Note also that you can define your method like this if you want to:
```
new @0 Request -> Result;
```
That would give you one less layer to unwrap.

**Comment by procyclinsur** [comment]
@dwrensha Thank you for your quick response It got me the builder very nicely!! 

I will also try out the new method definition!  Thanks again...
