### ISSUE TITLE
Why is `ReadStream` 'static ?

### ISSUE THREAD

**Issue by jannickj** [capnproto/capnproto-rust#170]
I'm trying to use ReadStream together with tokio, and I am getting an error that my `UnixSocket` doesn't live long enough, because it's not `'static`, unless there is something I misunderstand this seems very wrong. A Socket or any sort of stream should never be forced to stay a live for the entire program's lifetime.

In most cases 'static requirement is a code smell and only in rare cases should it ever be a hard requirement.

**Comment by dwrensha** [comment]
The `'static` is mostly a holdover from the olden days when Rust didn't have `Pin`. Removing it, as in #171, makes sense to me.

**Comment by dwrensha** [comment]
#171 has landed.
