### ISSUE TITLE
Support for "unwrapping" clients to get at the underlying server.

### ISSUE THREAD

**Issue by zenhack** [capnproto/capnproto-rust#172]
I'm experimenting with implementing Sandstorm's `WebSite` interface from `web-publishing.capnp`, and am unsure how to deal with the way uploading large blobs works. See:

https://github.com/sandstorm-io/sandstorm/blob/d366557c18faa085410334908a240ec88f97910b/src/sandstorm/web-publishing.capnp#L45-L46

and:

https://github.com/sandstorm-io/sandstorm/blob/d366557c18faa085410334908a240ec88f97910b/src/sandstorm/web-publishing.capnp#L81-L88

The interface suggests a flow where:

1. `uploadBlob` hands back a bytestream and blob to the caller
2. The caller writes the data to the bytestream
3. The caller passes the blob back to the server
4. The server then somehow identifies that this is one of the blobs it had previously handed out.

The last point suggests needing to be able to 'unwrap' a client to get at an underlying server (if the server is inside the local vat). I don't know how to do this this with the rust bindings, and am not sure whether it is in fact possible? Afaik the Go implementation doesn't do this either, and I just added this to the Haskell implementation a couple days ago. I'm not actually 100% sure whether the C++ implementation can do this, or if so, how (@kentonv?)

Can the rust implementation do this? If not, how difficult do you think it would be to add?

**Comment by kentonv** [comment]
In C++ you can do this using `CapabilityServerSet`.

**Comment by dwrensha** [comment]
There is no equivalent of `CapabilityServerSet` yet in Rust. I don't know how difficult it would be to add.

**Comment by dwrensha** [comment]
[`CapabilityServerSet`](https://github.com/capnproto/capnproto/blob/1db1e9f01a8d9dc065b58b8c47b16fbded86859c/c%2B%2B/src/capnp/capability.h#L527-L553) requires downcasting, which Rust does not support in the way that C++ does.

In the case of `web-publishing.capnp`, I think we can get away with something simpler. Instead of adding a way to recover the `Server` object, we could add a way to recover some associated data, which could either be a key identifying the capability, or a shared reference to some of the capability's inner state.

```rust
struct CapabilityAssociatedDataSet<T> {
   // ...
}

impl <T> CapabilityAssociatedDataSet<T> {
    /// Creates a new capability from a `Server` and some associated data.
    pub fn create<C: FromClientHook>(s: Box<dyn capability::Server>, data: T) -> C;

    /// Retrieves data assocated with a capability that was created with this
    /// CapabilityAssociatedDataSet. If the capability was not created with this
    /// set, returns `None.`
    pub async fn get_data(c: &capability::Client) -> Option<&T>
}
```

There are some details to work out, but I think this would be a fairly straightforward feature to add.

**Comment by kentonv** [comment]
Rust doesn't support downcasting? What are you supposed to do instead?

> we could add a way to recover some associated data, which could either be a key identifying the capability, or a shared reference to some of the capability's inner state.

Why can't be associated data be a reference to the server object itself?

**Comment by zenhack** [comment]
Indeed, I suspect it's at least possible to make the API as complete as
it is in C++ with no rtti -- per the docs downcasting is not possible
there either, but it's still possible to unwrap a client as the type
parameter for the CapabilityServerSet.

Quoting Kenton Varda (2020-04-28 19:39:16)

**Comment by kentonv** [comment]
To be fair, the C++ implementation doesn't need RTTI because the implementation already knows through other means whether the `Client` came from a particular `CapabilityServerSet`, so it can perform a static (rather than dynamic) downcast. But I would expect that a static downcast is "unsafe" in Rust.

**Comment by dwrensha** [comment]
> Why can't be associated data be a reference to the server object itself?

You can get a reference to the the `dyn capability::Server`, but you can't convert that into a reference to the underlying concrete type.

**Comment by zenhack** [comment]
Can we make use of `Any` for this?

https://doc.rust-lang.org/std/any/trait.Any.html

The Haskell implementation does something similar with Haskell's `Typeable`; perhaps local clients could hang on to a `dyn Any` in some fashion? We may not even need the set part of this.

**Comment by dwrensha** [comment]
OK, I think I see a way to make `CapabilityServerSet` work. I put up some first steps in #174.

The new `IntoClient` trait should make it possible for a `CapabilityServerSet` to get a handle on a `ServerDispatch` object, which it can then wrap in an `Rc<Refcell<>>`, passing one ref on to make a capability client, and retaining one ref to allow `get_local_server()` to be implemented.

**Comment by dwrensha** [comment]
A crucial finesse here is that the `Rc<Refcell<>>` should wrap the thing (i.e. `ServerDispatch`) implementing the base `capnp::capability::Server` trait, rather than the thing implementing the particular `foo::Server` trait from the generated code. Then we can use a blanket impl:

```rust 
impl <S: capnp::capability::Server> capnp::capability::Server for Rc<RefCell<S>> { ... }
```
whereas doing something similar with the `foo::Server` trait would require generating a bunch more code to forward each method.

**Comment by dwrensha** [comment]
I've landed #174. The new trait is now `FromServer`, not `IntoClient`: 
https://github.com/capnproto/capnproto-rust/blob/4271dca53868927cc580cc06df92aa6d6ac637c6/capnp/src/capability.rs#L254-L260

**Comment by zenhack** [comment]
Nice, looks like this will make the API more ergonomic too.

**Comment by zenhack** [comment]
Hm, I tried updating my existing code to use the new API, but it's giving me errors like:

```
error[E0277]: the trait bound `sandstorm::util_capnp::assignable::setter::Client<capnp::struct_list::Owned<sandstorm::web_publishing_capnp::web_site::entity::Owned>>: capnp::capability::FromServer<lmdb_web_site::EntitiesCell>` is not satisfied
   --> src/lmdb_web_site.rs:91:34
    |
91  |         results.get().set_setter(capnp_rpc::new_client(ret));
    |                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `capnp::capability::FromServer<lmdb_web_site::EntitiesCell>` is not implemented for `sandstorm::util_capnp::assignable::setter::Client<capnp::struct_list::Owned<sandstorm::web_publishing_capnp::web_site::entity::Owned>>`
    | 
   ::: /home/isd/.cargo/registry/src/github.com-1ecc6299db9ec823/capnp-rpc-0.12.2/src/lib.rs:320:45
    |
320 | pub fn new_client<C, S>(s: S) -> C where C: capnp::capability::FromServer<S> {
    |                                             -------------------------------- required by this bound in `capnp_rpc::new_client`
```

The change triggering the error is here:

https://github.com/zenhack/sandstorm-webpub-sysgrain/commit/672139d208fe3c87593fe70a1c7707c14e990bc1

Any idea what's going on? I'm at a loss.

**Comment by dwrensha** [comment]
Try `cargo update -p capnpc`.

**Comment by zenhack** [comment]
That did the trick, thanks.
