### ISSUE TITLE
Support for namespaced module generation

### ISSUE THREAD

**Issue by samuela** [capnproto/capnproto-rust#173]
Right now if you try to include a generated rust capnp module outside the root module, you run into some problems:
```rust
 // In src/newworld/mod.rs
pub mod filetree_capnp {
  include!(concat!(env!("OUT_DIR"), "/src/newworld/filetree_capnp.rs"));
}
```
```rust
// In build.rs
fn main() {
  ::capnpc::CompilerCommand::new()
    .file("src/newworld/filetree.capnp")
    .run()
    .unwrap();
}
```
We get a bunch of errors like:
```
error[E0433]: failed to resolve: unresolved import
 --> /opt/nuvemfs/cli/cargo-target-dir/debug/build/nuvemfs-cli-c1dfeda28eaf92b2/out/src/newworld/filetree_capnp.rs:9:67
  |
9 |   pub type HeartbeatParams<> = ::capnp::capability::Params<crate::filetree_capnp::peer::heartbeat_params::Owned>;
  |                                                                   ^^^^^^^^^^^^^^
  |                                                                   |
  |                                                                   unresolved import
  |                                                                   help: a similar path exists: `crate::newworld::filetree_capnp`
```

**Comment by dwrensha** [comment]
Hi! Did you try using the [`Rust.parentModule`](https://github.com/capnproto/capnproto-rust/blob/8e63130c4b35f9ac441058f331270ab97ef521ae/capnpc/rust.capnp#L13) annotation? It was added just a few days ago. See #16.

**Comment by samuela** [comment]
I tried following along with the example, so now I have
```capnp
@0xa850d6aba0560467;

using Rust = import "rust.capnp";
$Rust.parentModule("newworld");

interface Peer {
  heartbeat @0 ();
}
```
but I'm getting a capnp compilation error:
```
src/newworld/filetree.capnp:3:21-33: error: Import failed: rust.capnp
src/newworld/filetree.capnp:4:2-6: error: Not defined: Rust
```

**Comment by dwrensha** [comment]
You'll need to have `rust.capnp` in the include path somehow. I recommend just copying it over to wherever the rest of your schema files are.

**Comment by samuela** [comment]
Hmm, I see... Is there any way that `capnpc::CompilerCommand` could inject `rust.capnp` into the include path at build time?

**Comment by dwrensha** [comment]
I think the ideal solution would involve something like this: https://github.com/rust-lang/cargo/issues/3544

Another thing we might try is to get `rust.capnp` included alongside `c++.capnp` in the binary packaging of the [`capnp` tool](https://capnproto.org/capnp-tool.html).

If we're really ambitious, we could rewrite the capnp tool in Rust and inject `rust.capnp` there, but that would be a lot of work.

Aside from those approaches, I think the best we can do for now is to copy `rust.capnp` into a temporary directory and to pass that directory as a `-I` parameter to the `capnp` tool. I'm a bit reluctant to do that, though, as it seems hacky.

**Comment by samuela** [comment]
> Aside from those approaches, I think the best we can do for now is to copy rust.capnp into a temporary directory and to pass that directory as a -I parameter to the capnp tool. I'm a bit reluctant to do that, though, as it seems hacky.

Yeah it does seem a bit hacky... It's not ideal but I'm ok with having things at the root of my project for now, so I think I'll revisit this once it get too unwieldy.

**Comment by dwrensha** [comment]
Closing, because `parentModule` addresses this issue. If you have other, more specific problems, please open new issues for them.

I've added a few doc comments: https://github.com/capnproto/capnproto-rust/commit/998510cc3d79096df2e62dc0c9156111e7279f45.
