### ISSUE TITLE
static lifetime for client and server

### ISSUE THREAD

**Issue by b00f** [capnproto/capnproto-rust#176]
Client and Server implementation has static lifetime. This cause real trouble if an instance has a _mutable_ reference to  another item. This probably related to #170 and #171. 
Using `lazy_static` crate might mitigate this problem, however having mutable static item is another headache.

**Comment by dwrensha** [comment]
The usual workaround for this is to wrap the shared mutable state in `Rc<RefCel<T>>`. Does that work for you?

**Comment by b00f** [comment]
I didn't try it. I am thinking how can I re design my wheel again! 
Fixing this issue will be great.

**Comment by b00f** [comment]
@dwrensha , The workaround I found is using `Arc<Mutex<T>>`. 
`Rc<RefCell<T>>` won't work because of threading. right?

**Comment by dwrensha** [comment]
Depends on what the rest of your program is doing. I often find that `Rc<RefCell<T>>` is sufficient. For example: https://github.com/capnproto/capnproto-rust/blob/23ee18c5844cd4ab39dfb8aea05f757cad79d609/capnp-rpc/examples/pubsub/server.rs#L51

**Comment by b00f** [comment]
@dwrensha may I have your email address? Still I couldn't find a solution for my problem here: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/capnproto/r-KjPyXfoY0
