### ISSUE TITLE
maybe a missing crate `core`

### ISSUE THREAD

**Issue by drahnr** [capnproto/capnproto-rust#187]
Upgrading from `0.12` to `0.13` causes the following (unsettling errors, `core` should _always_ always be available):

```bash
# rustc --version
rustc 1.44.0 (49cae5576 2020-06-01)`
```

```text
error[E0433]: failed to resolve: maybe a missing crate `core`?
    --> /media/supersonic1t/projects/spearow/juice/target/release/build/juice-4ee9b139a8580f85/out/juice_capnp.rs:2760:91
     |
2760 |     fn get_from_pointer(builder: ::capnp::private::layout::PointerBuilder<'a>, default: ::core::option::Option<&'a [capnp::Word]>) -> ::capnp::Result<Builder<'a,>> {
     |                                                                                           ^^^^ maybe a missing crate `core`?
```

https://github.com/spearow/juice/pull/97/files#diff-fc04e529186c96cc603c2d379ce63b7dR32

---

Steps to reproduce (as in PR https://github.com/spearow/juice/pull/97 ):
```zsh
git clone --branch drahnr-features-tags-and-releases git@github.com:spearow/juice.git juice
cd juice
cargo b --no-default-features --features=native
```
assuming you have [`sd`](https://crates.io/crates/sd) installed 

```
sd '=\s*"0.13"' '= "0.12"' ./juice/Cargo.toml
```

will make compilation work again. Let me know if you need any further information.

**Comment by dwrensha** [comment]
Does it work if you add `extern crate core;` at the top of your crate?

I think that's necessary in Rust 2015, but not in Rust 2018. (So another way to avoid these errors would be to add `edition = "2018"` to your `Cargo.toml`.)

**Comment by drahnr** [comment]
Frankly, I forgot about the limitations of 2015 - thanks! I had the 2018 migration on my TODO anyways, if that does not solve it, I will re-open this. Thanks!

**Comment by drahnr** [comment]
Did the trick, thanks!
