### ISSUE TITLE
How to copy the data and own it, after reading

### ISSUE THREAD

**Issue by gjcarneiro** [capnproto/capnproto-rust#190]
I'm still running Rust, so maybe I miss something obvious, but...
After calling `serialize::try_read_message`, I get a `message::Reader<OwnedSegments>` value.

For the life of me, I cannot figure out how to store object that I just read into a HashMap.  Preferably minimising the number of memory copies, but I can't seem to be able to make a copy either.

I tried using into_segments(), to no avail:

```
error[E0382]: borrow of moved value: `message_reader`
   --> src/main.rs:101:19
    |
95  |         let message_reader = serialize::try_read_message(
    |             -------------- move occurs because `message_reader` has type `capnp::message::Reader<capnp::serialize::OwnedSegments>`, which does not implement the `Copy` trait
96  |             &mut *stream, options)?.unwrap();
97  |         let msgcopy = message_reader.into_segments();
    |                       -------------- value moved here
```

Any hints appreciated.

**Comment by dwrensha** [comment]
To copy a message, you can construct a new `message::Builder` and use `set_root()`. Something like this:

```rust
  let v : capnp::any_pointer::Reader = message_reader.get_root()?;
  let mut message_builder = capnp::message::Builder::new_default();
  message_builder.set_root(v)?;
```

**Comment by gjcarneiro** [comment]
Thanks!

Hm.. it is kind of slow though :/  The program reads over 1 million messages in  473.57ms, but when I add this copy, it takes 1.43s :(

**Comment by dwrensha** [comment]
It might help to use [`first_segment_words`](https://github.com/capnproto/capnproto-rust/blob/master/capnp/src/message.rs#L413) to control the size of the memory allocated in the `message::Builder`. You would then use [`message::Builder::new()`](https://github.com/capnproto/capnproto-rust/blob/aca4c478df17a7bfb6a0b98b43ff5b56444f0744/capnp/src/message.rs#L301) rather than `new_default()`.

**Comment by gjcarneiro** [comment]
I tried that, didn't pay off. Thanks anyway! :+1:

**Comment by gjcarneiro** [comment]
Oh wait, it makes little difference in CPU time, but makes a huge difference in memory consumption (from 5115 MB to 841 MB), so, good shout! :)

Code I'm using:

```rust
    let v : capnp::any_pointer::Reader = message.get_root()?;
    let allocator = capnp::message::HeapAllocator::new()
        .first_segment_words(message.get_root::<my_message::Reader>()?.total_size()?.word_count as u32)
        .allocation_strategy(capnp::message::AllocationStrategy::FixedSize);
    let mut message_builder = capnp::message::Builder::new(allocator);
    message_builder.set_root(v)?;
```

**Comment by gjcarneiro** [comment]
As an aside, why do I need to do `word_count as u32`?  It would be better to be consistent in the API: 
1. HeapAllocator::first_segment_words takes u32;
2. But total_size() in messages return u64.

Would be nicer if they had the same type, so that we wouldn't have to do casts and result checks.

**Comment by dwrensha** [comment]
2^29 is the maximum number of words allowed in a segment, so `u32` seems appropriate there, but a message can have more than 8 segments, so ` u64` is needed.
