### ISSUE TITLE
Higher RPC protocol levels

### ISSUE THREAD

**Issue by benbrittain** [capnproto/capnproto-rust#192]
Are there any plans to support more protocol levels? Persistent capabilities in particular would be a nice addition

**Comment by dwrensha** [comment]
My understanding is that capnproto-rust does not actually need to provide special support for persistence -- you can write your own `save()` and `restore()` implementations and they should just work. See https://groups.google.com/forum/#!msg/capnproto/d6uPbXf9e4E/CpmdqYuEAQAJ

For more advanced persistence features, I think that some of the stuff in [`membrane.h`](https://github.com/capnproto/capnproto/blob/0050fd757683f140b4a07fdc3eab986db0d00c8d/c%2B%2B/src/capnp/membrane.h) might be relevant, but I don't remember the details. I don't have any specific short term plans to port that stuff, but I would be curious to hear if you have a use case that demands it.

**Comment by benbrittain** [comment]
Thank you for that link! It cleared up a chunk of my confusion :)

**Comment by dwrensha** [comment]
👍
Closing. If you would like to track progress on specific features, please open new issues for them.
