### ISSUE TITLE
Please make capnp::serialize::write_message_segments take a reference for writer

### ISSUE THREAD

**Issue by gjcarneiro** [capnproto/capnproto-rust#193]
Maybe I'm too stupid to figure it out, but for the life of me I can't see how to use capnp::serialize::write_message_segments(), since it takes "writer" parameter by value.  So I write a message, but the function steals my writer, and my data, I cannot retrieve it afterwards.  Not good.  How does anyone ever managed to use this?

Request, change the signature of the method to take a mutable reference:
```
- pub fn write_message_segments<W, R>(write: W, segments: &R) -> Result<()> 
+ pub fn write_message_segments<W, R>(write: &mut W, segments: &R) -> Result<()> 
```

**Comment by dwrensha** [comment]
There is a blanket impl like this:
```
impl<W: Write + ?Sized> Write for &mut W { ... }
```

That means that `&mut W` implements `Write` when `W` does. So if you should be able to call `write_message_segments(&mut w, s)`. Does that work for you? If not, then what error do you get?

**Comment by gjcarneiro** [comment]
Never mind, I was being stupid.

My code was something like:

```python
fn capnp_to_python<'p>(
    py: Python<'p>,
    segments: &Arc<capnp::serialize::OwnedSegments>,
) -> &'p PyBytes {

    let cur = Cursor::new(Vec::<u8>::new());
    use capnp::serialize::write_message_segments;
    write_message_segments(&cur, &**segments).unwrap();
    let data = cur.into_inner();
    PyBytes::new(py, &data)
}
```

And I was getting this confusing error message:

```
error[E0277]: the trait bound `&std::io::Cursor<std::vec::Vec<u8>>: std::io::Write` is not satisfied
   --> src/pyext.rs:41:5
    |
41  |     write_message_segments(&cur, &**segments).unwrap();
    |     ^^^^^^^^^^^^^^^^^^^^^^ the trait `std::io::Write` is not implemented for `&std::io::Cursor<std::vec::Vec<u8>>`
    | 
```

But making the cursor mut solved it!

Thanks, and sorry for the silly question :facepalm:
