### ISSUE TITLE
Best way to add more more data to a List(Data)

### ISSUE THREAD

**Issue by sezaru** [capnproto/capnproto-rust#200]
Hello there, first of all, thank you for this amazing library it really helped me optimize "hot code path" I will describe bellow!

I'm using your library to serialize and deserialize data to be stored and retrieved from RocksDB, the idea is that I have the following struct:
```capnp
@0xbfbfe75b81832a9e;

struct Bucket {
    items @0 :List(Data);
}
```
This `List(Data)` will contain some binary data. New binary data can be added which will make the list grow.

Now, my question is, what is the optimal way to do the following when the client wants to add a new item to this list:
* Retrieve the serialized `Bucket` struct;
* Deserialize it;
* Grow the `items` list to have capacity for the new items;
* Add the new items;
* Serialize it back.

I already have a solution for it, but I wonder if there is a way to optimize it further since this is a very "hot code path" in my program:

```rust
// Retrieve the serialized `Bucket` struct and deserialize it

... Get binary data from RocksDB to variable value ...

let mut reader = &*value;

let message =
  capnp::serialize::read_message(&mut reader, ReaderOptions::new()).unwrap();

// Extract the items list

let root = message.get_root::<SerializedBucket::Reader>().unwrap();

let old_items = root.get_items().unwrap();

let mut new_list = Bucket::new();

old_items.iter().for_each(|v| {
  let vv = &v.unwrap();
  new_list.push(vv.to_vec())
});

// Append the new values to new_list

new_list.append(new_values);

// Create a new message Builder to store the new_list

let mut builder = Builder::new_default();

{
   let root = builder.init_root::<SerializedBucket::Builder>();
   let mut items = root.init_items(new_list.len() as u32);

   new_list
       .iter()
       .enumerate()
       .for_each(|(i, v)| items.set(i as u32, v));
}

let mut buf = Vec::new();

capnp::serialize::write_message(&mut buf, &builder).unwrap();

... Save variable buf to RocksDB ...
```

The issues that I see with my solution is that I first need to create a new list, add all old values to it via iteration, append the new values, and then, via iteration again, add this values to the new builder.

Seems to me that the ideal solution would be to somehow reutilize the read message just growing its items list and adding the new data without needing to create new vectors and/or new builders.

One thing that I didn't mention before for simplicity is that this list has a fixed max size that I can configure, for example, 50 items, this means that when the current struct list reaches 50 items, I will create a new `Bucket` struct to store the new data.

With that in mind, one thing that I thought would maybe improve performance would be to add a `size` field to `Bucket` struct and always have the `items` list size be the max size (50 in this case), that would allow me to simply retrieve the struct, set the new items without needing to grow the list (since it is already at max capacity) and then save the same struct back to rocksDB.

The problem with the above solution is that I'm not sure how to "convert" the reader struct into a builder one without allocation a brand new builder which would probably defeat the whole strategy.

So, I know this post is not an issue per see, but I really appreciate if you can give me some tips and suggestions on how to optimize the code in this scenario.

Thanks again!

**Comment by dwrensha** [comment]
There may be more details to your setup than the example code shows, but it looks to me like you can avoid the separate copy into `new_list` by directly copying into `builder`, like this:

```rust
// Retrieve the serialized `Bucket` struct and deserialize it

... Get binary data from RocksDB to variable value ...

let mut reader = &*value;
let message =
  capnp::serialize::read_message(&mut reader, ReaderOptions::new()).unwrap();

let root = message.get_root::<SerializedBucket::Reader>().unwrap();
let old_items = root.get_items().unwrap();
let mut builder = Builder::new_default();
{
   let root = builder.init_root::<SerializedBucket::Builder>();
   let mut items = root.init_items(old_items.len() + new_values.len());

   // TODO use iterators
   for ii in 0..old_items.len() {
      items.set(ii, old_items.get(ii));
   }
   for ii in 0 .. new_values.len() {
      items.set(ii + old_items.len(), new_values[ii]);
   }
}

let mut buf = Vec::new();
capnp::serialize::write_message(&mut buf, &builder).unwrap();

```

**Comment by dwrensha** [comment]
> The problem with the above solution is that I'm not sure how to "convert" the reader struct into a builder one without allocation a brand new builder which would probably defeat the whole strategy.

There's currently no way to avoid copying the bytes into a new builder. Note that you can precisely control the size of the new builder's initial allocation via [`first_segment_words`](https://github.com/capnproto/capnproto-rust/blob/74f16e84aa48c128a7cf5188c9d7a33f0697c225/capnp/src/message.rs#L423).

**Comment by sezaru** [comment]
Thank you for the suggestion! This is faster than my current solution and simpler too.
