### ISSUE TITLE
Unsound use of unsafe

### ISSUE THREAD

**Issue by benaubin** [capnproto/capnproto-rust#202]
https://github.com/capnproto/capnproto-rust/blob/7ecb112614f2ddb355800f85e32720107112df78/capnp/src/data.rs#L37

This is an extremely unsound use of unsafe. Exposing it publicly makes it possible to write unsound code from safe rust. This function should be marked as unsafe. Uses of this function should be wrapped in an unsafe block.

https://doc.rust-lang.org/nomicon/safe-unsafe-meaning.html

**Comment by dwrensha** [comment]
Thanks for the report!

Fixed in be7beab6091b7ac830bed72c6fb25295980b03fc.

**Comment by benaubin** [comment]
@dwrensha Awesome! This is a lot better. Could you mark it as `unsafe` rather than `pub(crate)`? Safe code in Rust should never never be able to cause undefined behavior - even in private apis (otherwise programs get hard to reason about and the compiler might do weird stuff). It'd be better to mark the function `unsafe` and wrap usages in an `unsafe` block.
