### ISSUE TITLE
capnp::serialize::compute_serialized_size_in_words returns size in bytes?

### ISSUE THREAD

**Issue by 6xzo** [capnproto/capnproto-rust#203]
Does `capnp::serialize::compute_serialized_size_in_words` return the size in bytes instead of 8-byte words? The documentation for it says "Returns the number of words required to serialize the message." I think that the similar function in other languages returns the 8-byte word size.

**Comment by dwrensha** [comment]
It should return the number of 8-byte words, but it's possible that the [0.12 release](https://dwrensha.github.io/capnproto-rust/2020/01/19/new-feature-to-allow-unaligned-buffers.html) introduced a bug.

**Comment by dwrensha** [comment]
Fixed in 5afd805528ae8df5eb78407c926fb615e1e5fe97.

Thank you!

**Comment by 6xzo** [comment]
Thank you.
