### ISSUE TITLE
Lists are limited to 2**29 elements

### ISSUE THREAD

**Issue by aetherrine** [capnproto/capnproto-rust#205]
I'm trying to pass an u8 slice through a rpc function by `request.get().set_val(value);`
The function is defined as `send @1 (val :Data) -> (answer :Data);` in the schema file.  
When `value` gets larger, the program terminates with the error in the title 'Lists are limited to 2**29 elements', ....../capnp-0.7.5/src/private/layout.rs:185:9. 
Is there a way to go beyond this limit and send larger data? Thanks in advance!

**Comment by dwrensha** [comment]
That limit is baked into the encoding: https://capnproto.org/encoding.html#lists

The only way to get around it is to break your list into smaller pieces.

**Comment by aetherrine** [comment]
I see. Thanks!
