### ISSUE TITLE
Support for returning a reference to primitive fields?

### ISSUE THREAD

**Issue by vlovich** [capnproto/capnproto-rust#207]
I'm fairly new to Rust so I may be misunderstanding something but is there a way to retrieve a reference to primitives that has the same lifetime as the underlying message (on little-endian platforms obviously)? It seems like all the accessors for primitives return temporaries? Or at least when accessing union members/in asynchronous mode? I haven't explored this part fully.

An example:

```
struct Foo {
    :union {
      a @0 :UInt8;
      b @1 :UInt16;
    }
}
```

```
// my_file is a std::File
let maybe_message_reader =
        capnp_futures::serialize::read_message(my_file, capnp::message::ReaderOptions::new()).await?
match maybe_message_reader {
    Some(ref message_reader) => {
         let header = message_reader.get_root::<my_capnp::foo::Reader>()?;
         let byte_slice = match header.which()? {
            my_capnp::foo::Which::A(ref value) => /* convert value to &[u8] */,
            my_capnp::foo::Which::B(ref value) => /* convert value to &[u8] */,
         };
         // operate on slice of bytes.
    },
    None => /* How should I handle this? */ Err(...)
}
```

I'm transcribing the Rust code I used rather than the exact one so there may be bugs & the slice conversion is elided since I've since deleted the code (took me a while to figure out). The complaint I got was that the lifetime of the slice I created exceeded the lifetime of a temporary making me think it was storing it by value. Indeed, reading the generated code I see the `Which` enum is  storing the primitive by value. I think this extends beyond unions though - AFAICT `get_data_field` also returns it by-value so I think there's no way to access primitives without generating a copy. Thus I'm getting this is intentional due to primitives like this being more efficient to pass around by value?  Does it make sense perhaps to allow accessing it by-reference, at least for Builders to provide something returning a mutable reference to avoid the overhead fo setting it? Setting a union field is two writes to the underlying message even when not changing the type of the union.

**Comment by dwrensha** [comment]
The closest thing we have right now is [`raw::get_struct_data_section()`](https://github.com/capnproto/capnproto-rust/blob/32898930518e10d2df41e7b141c76ac3617a0544/capnp/src/raw.rs#L26).

**Comment by dwrensha** [comment]
> Does it make sense perhaps to allow accessing it by-reference, at least for Builders to provide something returning a mutable reference to avoid the overhead fo setting it? Setting a union field is two writes to the underlying message even when not changing the type of the union.

There might be a small amount of performance benefit to that, but my feeling is that it wouldn't be worth the added complexity (including additional generated code) needed to support it.

Cap'n Proto optimizes for write-once usage patterns. If you are mutating messaging in place, then there are other annoying things you'll need to deal with too -- for example, reallocating lists will leave unclaimed space. If these things end up being too much of a problem, then I suggest reading your data into a native Rust struct and mutating that in place.
