### ISSUE TITLE
Why does constructing an async reader return a Result<Option>?

### ISSUE THREAD

**Issue by vlovich** [capnproto/capnproto-rust#208]
`read_message` in the asynchronous version return a `Result` of an `Option` but there's no documentation describing why it's optional (vs the synchronous version that just returns a `Result`) or what the `None` state represents. What does the `Option` represent & how should I handle the `None` state?

**Comment by dwrensha** [comment]
Thanks for the report!

`None` means that the end of the stream has been reached.

Fixed in https://github.com/capnproto/capnproto-rust/commit/32898930518e10d2df41e7b141c76ac3617a0544

**Comment by vlovich** [comment]
Oh interesting. Can you help me understand why the synchronous version doesn't return an `Option` then? Wouldn't the same logic apply?

**Comment by dwrensha** [comment]
The base `capnp` crate has two `read_message` functions:

 - [`capnp::serialize::read_message()`](https://github.com/capnproto/capnproto-rust/blob/32898930518e10d2df41e7b141c76ac3617a0544/capnp/src/serialize.rs#L182-L185) does not return an option type 
 - [`capnp::serialize::try_read_message()`](https://github.com/capnproto/capnproto-rust/blob/32898930518e10d2df41e7b141c76ac3617a0544/capnp/src/serialize.rs#L194-L197) does return an option type

To be fully consistent with that, `capnp_futures::serialize::read_message()` should probably be renamed to `try_read_message()`.

**Comment by vlovich** [comment]
Ah. Ok. That definitely clears things up. Thanks for clarifying. I agree maintaining symmetry would make things a lot clearer. I'm guessing the lack of a non-try version in futures is just an oversight?

Should I make a patch to make it symmetrical? Could hide it behind a feature flag to avoid semver issues & the feature flag could be removed before 1.0?

**Comment by dwrensha** [comment]
If we want to do the renaming, I think the way to do it would be:
 1. deprecate the existing `capnp_futures::serialize::read_message()` (but don't change its type yet)
 2. add a new function `capnp_futures::serialize::try_read_message()` 
 3. when we eventually release v0.14, change the type of `capnp_futures::serialize::read_message()` so that it no longer returns an option

**Comment by dwrensha** [comment]
Steps 1 and 2 are in ab94ac0f1ac74e4b520f55019230d58e23b3bfb9.

**Comment by vlovich** [comment]
Awesome! Thanks for addressing it so quickly.

**Comment by dwrensha** [comment]
Step 3 is in fa92e2f7bf20385192f2b87691754689b8982df8. I plan to make a v0.14 release soon. (Probably within a week or so from now.)
