### ISSUE TITLE
Use core_io

### ISSUE THREAD

**Issue by indolering** [capnproto/capnproto-rust#211]
It would be slightly more ... conventional to use [core_io](https://crates.io/crates/core_io) instead of rolling your own.  Not sure how much it would impact binary size, but relibc/redox, byteorder, mbedtls, and bincode all use it.

**Comment by dwrensha** [comment]
It's possible that core_io would be a better choice. I got scared away from it, though, because it looks complicated.

In particular, I am puzzled by this part:

> The version of the source that corresponds to your compiler version will be selected automatically by the build script

and the fact that the build script brings in lots dependencies.

**Comment by dwrensha** [comment]
Do byteorder and bincode really use `core_io`? I don't see it list as a dependency at https://crates.io/crates/byteorder or https://crates.io/crates/bincode.

**Comment by indolering** [comment]
Oh, you are right.  I was looking [forks of those two](https://crates.io/crates/core_io/reverse_dependencies).  Might not be as popular as I thought.
