### ISSUE TITLE
Regression in 0.12 in capnp::serialize::compute_serialized_size_in_words

### ISSUE THREAD

**Issue by FrancisRussell** [capnproto/capnproto-rust#212]
I've been trying to track down a breakage that occurs when moving to the 0.12 release from a codebase that works fine with 0.9 onwards. I've tracked this down to a mismatch between the value returned by `capnp::serialize::compute_serialized_size_in_words` and amount of data then written to a buffer when the message is serialized.

In one case:
Value returned by `capnp::serialize::compute_serialized_size_in_words`: 113
Assumed size of message based on the above: 904 bytes
Amount of data written to buffer when serializing: 120 bytes

Reverting to 0.11:
Value returned by `capnp::serialize::compute_serialized_size_in_words`: 15
Assumed size of message based on the above: 120 bytes
Amount of data written to buffer when serializing: 120 bytes

While the returned value from 0.12 is around 4x the expected value, it doesn't seem to be the message size in bytes either.

**Comment by dwrensha** [comment]
I suspect that's the same bug as reported in #203, and fixed in the latest release capnp-v0.13.6.

**Comment by FrancisRussell** [comment]
Unfortunately I've encountered other issues trying to upgrade to 0.13 so was trying to get 0.12 fixed first.

**Comment by dwrensha** [comment]
We could backport 5afd805528ae8df5eb78407c926fb615e1e5fe97 and make a new patch release for 0.12.

**Comment by FrancisRussell** [comment]
I think that would be good. Seeing that 0.12 was updated this year and the previous releases available on crates.io don't have this issue, I think many might assume that 0.12 having this issue was an unknown bug.

**Comment by dwrensha** [comment]
Published: https://crates.io/crates/capnp/0.12.4.

**Comment by FrancisRussell** [comment]
Confirming that the fix in 0.12.4 works as expected. Thank you!
