### ISSUE TITLE
Expose capnp::private::units::BYTES_PER_WORD?

### ISSUE THREAD

**Issue by Ekleog** [capnproto/capnproto-rust#217]
Hello!

I'm trying to use capnp, and I see that `capnp::serialize::compute_serialized_size_in_words` is public but not `capnp::private::units::BYTES_PER_WORD`.

Is there any reason for this? Currently I'm hardcoding `8` in `BYTES_PER_WORD`, but it's not obvious that's how that should be for 32-bit targets (theoretically it should be `4`, but looking at the capnp source code it shows to be statically set to `8`, so…]

As another solution, exposing a `capnp::serialize::compute_serialized_size_in_bytes` would also work for me.

What do you think about this? Am I missing another way this should actually be done, to preallocate the right amount of memory before serializing into?

**Comment by dwrensha** [comment]
Thanks for the report!

"word" in a capnproto context means 8 bytes, regardless of the target architecture.
I've updated the doc comments to clarify: d53202a2db3ea942deb233684df687e8bedc4bdc.

You can either multiply by 8, or if you don't like hardcoding that constant,
you can multiply by `std::mem::size_of::<capnp::Word.()`.

**Comment by Ekleog** [comment]
Great, thank you!
