### ISSUE TITLE
Shared memory IPC

### ISSUE THREAD

**Issue by taylorjdawson** [capnproto/capnproto-rust#218]
Is there an example of and/or is it possible to implement shared memory IPC with this library?

**Comment by dwrensha** [comment]
I don't know of any examples. I suspect it should be possible using a custom implementation of [`capnp::message::Allocator`](https://github.com/capnproto/capnproto-rust/blob/eec64b6e55543fa4e6bdb047c49df957f764bdc3/capnp/src/message.rs#L273-L294).

This comment on the mailing list, referring to capnproto-c++, applies equally well to capnproto-rust: https://groups.google.com/g/capnproto/c/lIZcGLiBilY/m/M9U1-uugEQAJ

**Comment by taylorjdawson** [comment]
Excellent thank you.
