### ISSUE TITLE
why which() give me a error type ?

### ISSUE THREAD

**Issue by gcxfd** [capnproto/capnproto-rust#219]
the code is there
https://github.com/gcxfd/rust/tree/5b8ee287796a92b744a4b8b9c7ac5b6b34e97ccb

see the screenshot below

![image](https://user-images.githubusercontent.com/69608605/107713209-ad054580-6d05-11eb-8a09-f55acd6f8360.png)

why which() give me a error type ?

should ack but give me syn

**Comment by dwrensha** [comment]
Oh wow, interesting. I think it's a bug that capnproto-rust lets you do 
```rust
message.init_root::<msg::ack::Builder>();
```
`ack` is a group type, not a full struct type.


You need to do this instead:
```rust
let mut msg = message.init_root::<msg::Builder>();
let mut ack = msg.init_ack();
ack.set_pk(...);

```
