### ISSUE TITLE
Clarification on when to call init_* methods

### ISSUE THREAD

**Issue by bluk** [capnproto/capnproto-rust#222]
Are there any scenarios where you would want to call `init_{field_name}` versus only calling `get_{field_name}` with the `Builder` (especially for struct types)? I can understand for `List` fields where you need to give the fixed length ahead of time, but for fields with struct types, I don't understand why you call `init_{name}`. Any hints?

Reading the [C++ Serialization documentation](https://capnproto.org/cxx.html), it seems that `get_{name}` will always initialize a field. I assume the same is true in the Rust version.

Thanks for the library!

**Comment by dwrensha** [comment]
The `init_*` methods zero the object before returning. The `get_*` methods do not. In many cases it does not matter which method is used.

**Comment by bluk** [comment]
Thanks!
