### ISSUE TITLE
include LICENSE file in published crates

### ISSUE THREAD

**Issue by decathorpe** [capnproto/capnproto-rust#224]
The MIT License terms require that the license text is made available with any redistributed sources, which also means that the LICENSE file should be included in crates published to crates.io (capnp, capnpc, capnp-futures, capnp-rpc).

To have "cargo publish" pick the files up, adding symlinks `LICENSE → ../LICENSE` in each of the workspace member directories (at least those that are actually published) is enough.

**Comment by dwrensha** [comment]
Good point! Done in https://github.com/capnproto/capnproto-rust/commit/24938b7571ffc393f68d7b2b5c34fb7c780793f5.

**Comment by decathorpe** [comment]
Thank you!
