### ISSUE TITLE
Status response codes for error handling

### ISSUE THREAD

**Issue by seguidor777** [capnproto/capnproto-rust#244]
Hi,

I'm creating some microservices in Rust which use capnp-rpc for inter-service communication. Since I'm exposing the gateway microservice through http, I'd like to map the capnp error types to their correspondent http error code for example. 4xx or 5xx.
So far I've only seen the capnp::ErrorType with a few variants[1].
And I saw that gRPC has different kinds of response codes[2]. The most important to me would be: invalid argument, not found, already exists, permission denied and unauthenticated.
I'd like to have something similar in capnp-rpc to properly handle each response code from the gateway microservice to the end user.
My workaround is to always use the Failed variant and have to parse the description to know the specific error.

1. https://docs.rs/capnp/0.14.4/capnp/enum.ErrorKind.html
1. https://developers.google.com/maps-booking/reference/grpc-api/status_codes

**Comment by dwrensha** [comment]
Have you seen how Sandstorm encodes HTTP responses?
https://github.com/sandstorm-io/sandstorm/blob/bc0d98ee9f998a1606218b01db196d7744534a0f/src/sandstorm/web-session.capnp#L236-L450

The idea is to define a `Response` struct that is a `union` of the possibilities: either a successful response, or some kind of application-level error.

`capnp::Error` is intended to be reserved for lower-level errors.

**Comment by seguidor777** [comment]
Thanks for sharing that reference.
Actually, I was thinking about implementing something similar. This is the confirmation that I needed and answers my question.
