### ISSUE TITLE
Docs: which Cap'n Proto RPC level does this rust implementation satisfy?

### ISSUE THREAD

**Issue by OliverEvans96** [capnproto/capnproto-rust#264]
Hi there,

I just recently learned about cap'n proto and this library. The [RPC docs page](https://capnproto.org/otherlang.html) for the protocol breaks the total feature set up into 4 "levels" which implementations can advertise in order to succinctly communicate to users how much of the specification it implements.

Which level does this implementation satisfy? And would it be appropriate to add this information to the README?

Thanks!
Oliver

**Comment by dwrensha** [comment]
It's a level one implementation. The docs already mention that (though not in the top-level readme):
https://docs.rs/capnp-rpc/0.14.1/capnp_rpc/
https://github.com/capnproto/capnproto-rust/tree/master/capnp-rpc

**Comment by OliverEvans96** [comment]
Ah, thank you! Not sure how I missed that - it makes sense to include that in the RPC section since the "levels" explicitly refer to RPC features.

However, since I missed it, I imagine I'm not the only one. I created a [small PR](https://github.com/capnproto/capnproto-rust/pull/265) to mention it in the readme.
