### ISSUE TITLE
How to tick an rpc server?

### ISSUE THREAD

**Issue by Bvsemmer** [capnproto/capnproto-rust#271]
Hey,

I have been browsing the RPC examples in the capnproto crate. The examples are quite basic, in the sense that they never keep a RPC server alive. They run their RPC calls one after the other and shutdown the server afterwards.

So I was wondering about this, how do I run an RPC server continuously? That allows clients to keep sending messages.

My RPC server is setup like this (Using a very simple Handshake message schema now):
```
pub struct Handshake {
    pub client: handshake::Client,
}

impl Handshake {
    pub async fn setup(stream: tokio::net::TcpStream) -> Self {
        tokio::task::LocalSet::new()
            .run_until(async move {
                stream.set_nodelay(true).unwrap();
                let (reader, writer) =
                    tokio_util::compat::TokioAsyncReadCompatExt::compat(stream).split();
                let rpc_network = Box::new(twoparty::VatNetwork::new(
                    reader,
                    writer,
                    rpc_twoparty_capnp::Side::Client,
                    Default::default(),
                ));

                let mut rpc_system = RpcSystem::new(rpc_network, None);
                let client: handshake::Client =
                    rpc_system.bootstrap(rpc_twoparty_capnp::Side::Server);

                tokio::task::spawn_local(Box::pin(rpc_system.map(|_| ())));

                Self { client: client }
            })
            .await
    }

    pub async fn send(&self, msg: &str) {
        tokio::task::LocalSet::new()
            .run_until(async move {
                let mut req = self.client.say_hello_request();
                req.get().init_request().set_name(msg);
                tokio::task::spawn_local(async {
                    let reply = req.send().promise.await.unwrap();
                    println!(
                        "received: {}",
                        reply
                            .get()
                            .unwrap()
                            .get_reply()
                            .unwrap()
                            .get_message()
                            .unwrap()
                    );
                })
                .await
                .unwrap();
            })
            .await;
    }
}

```

But after this, what do I call to let the server keep processing incoming messages? I do not see any loop / processing calls in there.

If I, after this setup, connect with a client and try to send a request using the `send` function above then this line `let reply = req.send().promise.await.unwrap();` just hangs forever. Even more, when I debug the server, I never enter my `HandshakeImpl`. So somehow this send is failing silently.
```
impl handshake::Server for HandshakeImpl {
    fn say_hello(
        &mut self,
        params: handshake::SayHelloParams,
        mut results: handshake::SayHelloResults,
    ) -> Promise<(), ::capnp::Error> {
        let request = params.get().unwrap().get_request().unwrap();
        let name = request.get_name().unwrap();
        let message = format!("Hello, {}!", name);

        results.get().init_reply().set_message(&message);

        Promise::ok(())
    }
}
```

This is probably a beginners mistake, but I cannot work it out :) I hope someone here recognizes some common pitfalls.

**Comment by Bvsemmer** [comment]
Oh, and when I run 
```
let mut req = self.client.say_hello_request();
req.get().init_request().set_name(msg);
tokio::task::spawn_local(async {
    let reply = req.send().promise.await.unwrap();
    println!(
        "received: {}",
        reply
            .get()
            .unwrap()
            .get_reply()
            .unwrap()
            .get_message()
            .unwrap()
    );
})
.await
.unwrap();
```
in the `setup` function above (right after `tokio::task::spawn_local(Box::pin(rpc_system.map(|_| ())));`) the RPC works fine. So the connection between the client and server is definitely working. 
It's just when the message is sent later it fails.

**Comment by dwrensha** [comment]
This line is what gets the RPC task going:
```
tokio::task::spawn_local(Box::pin(rpc_system.map(|_| ())));
```

It will stop going once the enclosing `task::LocalSet` is dropped. So in your case, when `setup()` returns, the background RPC will have been stopped.

I expect it to work better if you pull the `task::LocalSet` out to a higher level of your program, so that it does not get dropped while you are still expecting to need to handle RPCs.

**Comment by Bvsemmer** [comment]
Hey, thanks for your answer! 

Yeah, in the meantime I realized this as well. 
Though I am struggling with the `task::LocalSet` part of this story. If I understand tokio correctly (quite new for me) a LocalSet is running on the main thread. So to prevent the main thread from blocking I would have to run this on a separate thread, don't I? 

Problem is that this RPC server seemingly cannot run on a separate thread at all, since some critical parts do not implement the Send trait. As soon as I try that, the Rust compiler starts complaining. 

What am I overlooking?

**Comment by dwrensha** [comment]
> So to prevent the main thread from blocking I would have to run this on a separate thread, don't I?

That's correct.

To interface between capnp-rpc and threaded code, you may need to set up communication along a `futures::channel::mpsc` sender/receiver pair. This can be annoying, because you may need to copy the RPC request and response data into new `Send` data structures.

It seems to be a pretty common desire that capnp-rpc ought to work better with threading. (See for example #180.) A substantial overhaul might be warranted.

**Comment by dwrensha** [comment]
Hm... one approach to interfacing between the single-threaded world of capnp-rpc and a multithreaded rest-of-your-program might be to implement an RPC client handle that satisfies `Send`.

Sketch:

``` rust
pub struct Handle<T, Output>
{
   tx: std::futures::mpsc::Sender<(Box<dyn FnOnce(&T) -> Box<dyn<Future<Output=Output>>>,
                                   std::sync::mpsc::Sender<Output>)>,
}

impl <T,Output> Handle<T,Output>
{
  // You need to run this constructor in the RPC thread on a `Client` object.
  // Then you can send the resulting handle to any thread.
  pub fn new(T) -> Self {
     let (tx, rx) = futures::channel::mpsc::channel();
     // spawn a tokio task that receives closures on `rx` and executes them
     // ....

    Handle { tx }
  }

  // Do some stuff with the underlying `Client` object on the RPC thread and return the result to the current thread.
  pub fn block_on<F>(&self, f : F) -> G::Output
    where F: FnOnce(&T) -> Box<dyn<Future<Output=Output>>> + Send + 'static
  {
    let (tx, rx) = std::sync::mpsc::sync_channel(1);

    // Send `f` for execution on the RPC thread.
    self.tx.try_send((Box::new(f), tx));

    // wait for the RPC thread to return the result 
    rx.recv()
  }
}
```

**Comment by dwrensha** [comment]
Closing, because it looks like the initial question was answered, and we have other issues to track the "multithreaded RPC" question, for example: https://github.com/capnproto/capnproto-rust/issues/143
