### ISSUE TITLE
code quality (linting and formatting)

### ISSUE THREAD

**Issue by danieleades** [capnproto/capnproto-rust#303]
It doesn't appear that linting or formatting are applied/checked in this repo. Would you be interested in pull requests for these?

I can split these into separate issues if you like. I think the value of auto-formatting is well documented, particularly for open-source projects.

clippy also is useful for catching both correctness and style issues. The following PRs are mostly fixes for various clippy lints

see:

- [x] #304 
- [x] #305 
- [x] #306 
- [x] #307 
- [x] #308 
- [x] #309 
- [x] #310 
- [x] #311 
- [x] #312 
- [x] #313 
- [x] #315
- [x] #317
- [x] #318 
- [x] #319 
- [x] #320 
- [x] #321 
- [x] #322
- [x] #325
- [x] #331

note that some of these may need to be rebased after others are merged (*if* they are merged, of course).

#305 in particular has potential to be a little hairy. that should probably go last, and also has the potential to cause headaches for other open PRs. My advice, rip the bandaid off. It'll save a lot of headaches in future.

**Comment by danieleades** [comment]
you can probably guess from the PRs that i'm gearing up to adding a linting job to CI, but first I need to make sure said job would actually *pass*

**Comment by dwrensha** [comment]
Autoformatting sounds good to me. I'm a bit more skeptical about Clippy, as it seems to make bad suggestions sometimes (e.g. https://github.com/capnproto/capnproto-rust/pull/312/files#r1020222229 ). I suppose we could add specific suppressions when we disagree with Clippy?

**Comment by danieleades** [comment]
>  suppose we could add specific suppressions when we disagree with Clippy?

exactly! better to opt out of specific lints than not have any linting, i think. I'll close the PR you reference, and when I open a PR to add automatic linting i'll suppress those warnings.

**Comment by danieleades** [comment]
getting very close now. Just a handful more lint errors and warnings to address and then linting can be added to CI

**Comment by dwrensha** [comment]
Closing, because all of the checkmarks are filled in. Thanks!
