### ISSUE TITLE
Invalid Rust generated if field and struct name share the same name

### ISSUE THREAD

**Issue by vlovich** [capnproto/capnproto-rust#329]
I have something like this:
```
struct Message {
  index :union {
    v0 @0 :Index;
  }

  struct Index {}
}
```
This seems to cause two module definitions called `index` in the generated Rust code:

```
458 |   pub mod index {
    |   ------------- previous definition of the module `index` here
...
783 |   pub mod index {
    |   ^^^^^^^^^^^^^ `index` redefined here
    |
    = note: `index` must be defined only once in the type namespace of this module
```

Not sure there's a way to solve this without breaking back compat but I figured I'd document it. Not a huge deal since names are are fluid in schemas, but a bit surprising (I haven't tried but I don't think the C++ generator has this problem).

**Comment by dwrensha** [comment]
capnproto-c++ has a similar issue: https://github.com/capnproto/capnproto/issues/19

In Rust you can work around such collisions by adding an annotation:
https://github.com/capnproto/capnproto-rust/blob/ccc0aab34bcf93c2d4fc671b23acfd1b0c644c9e/capnpc/rust.capnp#L9-L13

**Comment by vlovich** [comment]
Ah OK. Thanks! Sorry for the noise.
