### ISSUE TITLE
build generated files at compile time

### ISSUE THREAD

**Issue by danieleades** [capnproto/capnproto-rust#370]
some of the committed files are generated. Usually this is bad practice, and generated files should not be committed to the repo.

I note that the compiler (capnpc) itself depends on a generated file - `schema_capnp.rs`. That creates a circular dependency that means the file must be committed.

You can 'boostrap' the compilation after making changes to the code generation by generating a new version of `schema_capnp.rs` with a different version of the compiled capnpc.

Is there any way to eliminate this circular dependency so that these files can be removed from VCS and always generated on the fly?

**Comment by dwrensha** [comment]
I don't see a way to eliminate the circular dependency.

The capnp-rpc generated files got checked in after https://github.com/capnproto/capnproto-rust/issues/163. I think it's better this way, because it means that things like docs.rs and crater do not need to have the `capnp` tool installed.

I do think we could improve the current setup by adding a script for regenerating the code, so that the manual burden is reduced.

**Comment by danieleades** [comment]
> I don't see a way to eliminate the circular dependency.
> 
> The capnp-rpc generated files got checked in after #163. I think it's better this way, because (among other things) it means that things like docs.rs and crater do not need to have the `capnp` tool installed.
> 
> I do think we could improve the current setup by adding a script for regenerating the code, so that the manual burden is reduced.

you'd have to split the crate into two.

- a bin or lib target responsible for turning a schema file into a source file
- a bin crate which wraps the former and handles the incoming `request` to perform the generation

i believe the `schema_capnp.rs` is only required for the latter?

the current solution does both in a single compilation unit, hence the circularity.

**Comment by dwrensha** [comment]
added regeneration scripts here: https://github.com/capnproto/capnproto-rust/commit/acdc18473f28fa373651f98e4df0e912280754c0

**Comment by danieleades** [comment]
> added regeneration scripts here: [acdc184](https://github.com/capnproto/capnproto-rust/commit/acdc18473f28fa373651f98e4df0e912280754c0)

nice! that's a huge help.

Would also be good to have an action to check whether they are up to date

**Comment by dwrensha** [comment]
Closing. Getting rid of `schema_capnp.rs` seems impossible, and having `rpc_capnp.rs` and `rpc_twoparty_capnp.rs` makes `capnp-rpc` significantly more user friendly. The `regenerate-` scripts in the top level of the repo work well enough.
