### ISSUE TITLE
How do I convert a Reader to a TypedReader?

### ISSUE THREAD

**Issue by bdkiran** [capnproto/capnproto-rust#378]
I have been mulling around this issue for a while. Maybe my pattern is incorrect but it seems like what I want to do is possible.

My Approach
1) I have a Cap n Proto Message that contains a union to other messages(MessageEnvelope).

```
@0xa0042efeeed7bb94;

struct MessageEnvelope {
  union {
    myMessage @0 :myMessage;
   .......
  }
}

struct myMessage {
  myNumber @0 :UInt64;
}
```

2) Parse message func to map the Union message to the underlying message(MyMessage) that can be passed around in a channel(based on everything I've read including examples this needs to be done with a TypedReader)
3) Once in the channel, another function receives MyMessage and does what it pleases with the data.

```rust
pub fn parse_cap_message(data: Vec<u8>) -> NewCommand {
    // Deserializing object
   let reader = serialize::read_message(
        data.as_slice(),
        ReaderOptions::new()
    ).unwrap();
   // Message envelope is a type that contains other capnproto messages
    let message_envelope = reader.get_root::<message_envelope::Reader>().unwrap();
   // Match the type 
    match message_envelope.which() {
        Ok(message_envelope::MyRequest(my_request)) => {
            // Reader type
            let my_request_reader = my_request.expect("Unable to get my request from envelope");
            // Unable to cast Reader into TypedReader
            let topic_reader: TypedReader<Builder<HeapAllocator>, topic_request::Owned> = TypedReader::from(topic_request.into());
            // This is a type that we want to pass into a MSPC channel to handle the message elsewhere. That's why TypedReader is needed.
           NewCommand::TopicRequest { 
                capmessage: topic_reader
            }
        },
...
  }
}
```
How do I convert my Read type to TypedReader?

**Comment by dwrensha** [comment]
`TypedReader` currently only works for ascribing a type to the root of a message. You are attempting to ascribe a type to a value that is not the root of its message, so it's not going to work.

If you are willing to copy your data into a new message, you could create a `TypedBuilder` and fill it in with `set_root()`.

Alternatively, you could define your own wrapper type. A sketch:
```rust
struct Wrapper {
   message : TypedReader<message_envelope::Owned>,
}

impl Wrapper {
  pub fn get(&self) -> Result<my_message::Reader<'_>, capnp::Error> {
     if let message::envelope::MyMessage(inner) = self.message.get_root()? {
       inner
     } else {
       panic!("expected MyMessage")
     }
  }
}
```
Unfortunately, this entails the (small) runtime cost of re-checking the `which()` value on every call to `get()`. 

In principle, it could make sense for there to be a version of `TypedReader` that points to non-root data. I'm not sure how to make an API for it that would be easy to use, though.

**Comment by bdkiran** [comment]
Okay I ended up going with the TypedBuilder option. If I need to save on the copy I will implement the wrapper. Thanks for the response!
