### ISSUE TITLE
Document when write_message errors

### ISSUE THREAD

**Issue by danielzfranklin** [capnproto/capnproto-rust#391]
From skimming the code I think {serialize,serialize_packet}::write_message return Err only if the target Write::write_all does.

I'd like it if there was a documented guarantee the following would never panic

```rust
let mut out = Vec::new();
serialize::write_message(&mut out, message).expect("infallible writer");
```

**Comment by dwrensha** [comment]
Doc comments added in https://github.com/capnproto/capnproto-rust/commit/0b7a999f3811b3d5523a724fbc78bfdab05f53bd

Note however that, strictly speaking, your example could panic if the allocator is out of memory. :)
