### ISSUE TITLE
std::marker::PhantomData still used when using no_std

### ISSUE THREAD

**Issue by imccreadie** [capnproto/capnproto-rust#396]
When generating a file with a const struct with `no_std` it still uses `std::marker::PhantomData` in the generated file.

It might just be https://github.com/capnproto/capnproto-rust/blob/f82031359ebf4e8824d09d416f97d85890de74b1/capnpc/src/pointer_constants.rs#LL92C1-L92C1 being changed to `::core::marker::PhantomData`.

Example struct which results in `::std::marker::PhantomData` being used:
```
struct ConstData {
    value @0 :Text;
    name @1 :Text;
}

struct ConstContainer {
    entries @0 :List(ConstData);
}

const myConstData :ConstContainer = (
    entries = [
        (value="value1", name="Name1"),
        (value="value2", name="Name2"),
   ]
);
 ```

**Comment by dwrensha** [comment]
Thanks! Fixed in https://github.com/capnproto/capnproto-rust/commit/3b66078c50209df9362157517c49e13f73b459a6.
