### ISSUE TITLE
Enum fields with defaults generate bad setters

### ISSUE THREAD

**Issue by kenfred** [capnproto/capnproto-rust#398]
Fields that have default values in the schema are supposed to use an XOR mask when getting and setting values. This is so that an encoded struct will always be zeros by default.

Bug found in version 0.17:

When an enum is given a default value in the schema, the generated setter is not using the mask and therefore it is encoding with bad data.

[Please find an example here.](https://github.com/kenfred/capnpc_enum_default_bug)

Example schema:

```code
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("example");

struct Example {
  value @0 :Variants = two;

  enum Variants {
    zero @0;
    one @1;
    two @2;
  }
}
```

When you build the example, you can see in the generated code that the getter uses the mask, but the setter does not. This means all sets are corrupting and gets and sets will never agree.
```code
    #[inline]
    pub fn get_value(self) -> ::core::result::Result<crate::example_capnp::example::Variants,::capnp::NotInSchema> {
      ::core::convert::TryInto::try_into(self.builder.get_data_field_mask::<u16>(0, 2))
    }
    #[inline]
    pub fn set_value(&mut self, value: crate::example_capnp::example::Variants)  {
      self.builder.set_data_field::<u16>(0, value as u16)
    }
```

If you run `cargo test` on the package I provided above, you will see the encoding errors.

**Comment by dwrensha** [comment]
Thanks for the report!
Looks like we need to add some logic here: https://github.com/capnproto/capnproto-rust/blob/1ce11c2e9df9c50301a17d208d6ec457b2bf8a5e/capnpc/src/codegen.rs#L1006-L1012

**Comment by dwrensha** [comment]
Should be fixed by https://github.com/capnproto/capnproto-rust/pull/399.

**Comment by kenfred** [comment]
Wow, that was fast!

I can confirm that your fix generates what I would expect:
```code
    #[inline]
    pub fn get_value(self) -> ::core::result::Result<crate::example_capnp::example::Variants,::capnp::NotInSchema> {
      ::core::convert::TryInto::try_into(self.builder.get_data_field_mask::<u16>(0, 2))
    }
    #[inline]
    pub fn set_value(&mut self, value: crate::example_capnp::example::Variants)  {
      self.builder.set_data_field_mask::<u16>(0, value as u16, 2);
    }
```

And with your branch, those example tests I provided now pass.
