### ISSUE TITLE
Adding or Extending Clients in Rust code?

### ISSUE THREAD

**Issue by DTrippe** [capnproto/capnproto-rust#400]
Similar question to https://github.com/capnproto/capnproto-rust/issues/261:

Is it possible to extend a client with one that's already been compiled? For example, if I have some package "B" that depends on "A", and in "B" there is a `Common` interface. If I wanted to create a `Service` interface for package "A" that also has the functionality of the `Common` interface, is there any way of doing so with only access to the generated code from "B" (not the `.capnp` definitions)? 

In this scenario, there is no shared logic between those interfaces (as in, either could function independently of the other).

**Comment by dwrensha** [comment]
See #233. At schema-compilation time, `capnp compile` needs to be able to find the `.capnp` files of all types being referenced. So you are going to need to give it access to the `.capnp` files from package `B`.

**Comment by DTrippe** [comment]
Makes sense, thank you for the reply.
