### ISSUE TITLE
Question - It is possible expose more than one rpc interface throughout one socket?

### ISSUE THREAD

**Issue by 04l3x** [capnproto/capnproto-rust#416]
Hi,

I'm new with RPC protocols so probably my question may have some conceptual errors.

I'm trying to write a higher level library for cap'n proto for writing both servers/clients, something like tonic but over cap'n proto instead protobuf and runtime agnostic.

I would like have an interface pretty similar to tonic. Something like this for the server side.
```rust
use my_lib::server::Server;

use crate::services::{SomeService, SomeService2}; // ...SomeService3, 4, 5 .........

#[async_std::main]
async fn main() ->async_std::io::Result<()> {
    let service_1 = SomeService::new();
    let service_2 = SomeService2::new();

    Server::new()
        .add_service(service_1)
        .add_service(service_2) // add service 3, .. 4 ...  5 ... .... n
        .serve("0.0.0.0:4567").await?;

    Ok(())
}
```

To can call to whatever be, service_1 or service_2. 

But I'm a bit (well actually more than a bit...) stuck. 

I reproduced the hello_world example

```rust
#[async_std::main]
async fn main() -> async_std::io::Result<()> {
    let hello_world_client: hello_world::Client = capnp_rpc::new_client(HelloWorldImpl);

    let listener = TcpListener::bind("127.0.0.1:50070")
        .await
        .expect("failed to open listener");

    let mut incoming = listener.incoming();

    while let Some(stream) = incoming.next().await {
        let stream = stream.expect("failed to unwrap stream");

        let reader = stream.clone();
        let writer = stream;

        let network = twoparty::VatNetwork::new(
            reader,
            writer,
            rpc_twoparty_capnp::Side::Server,
            Default::default(),
        );

        let rpc_system = RpcSystem::new(Box::new(network), Some(hello_world_client.clone().client));

        async_std::task::spawn_local(rpc_system).await.expect("");
    }

    Ok(())
}
```

This works well when I run the client. But I'm trying to figure out how to put more than one service in the same server. My intuition tells to me that the `Server` struct should have a set of `Service`s (but also I have no idea how to represent a service) maybe something like `Vec<Service>` or maybe `HashMap<_?_, Service>` so the incoming stream should "be matched" to their own service - But honestly I have no idea.

My first attempt was to simply create a `hello_world_2` and have it placed in series next to `hello_world`, something like [this](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=100c83a61aaf8f13c379477cdd5dcc10).

And this does not work when you test it, only the client of the service that is placed first works. 

I understand that this behavior has to do with the flow of how the stream is processed, when the client of the second service calls the server the only interface that can read is the one of the first service, this brings me back to the beginning of my question, how to handle multiple RPC interfaces on a single server?

I'm sorry if this question is a bit silly, but I don't really understand how to define what a service or route is.

**Comment by dwrensha** [comment]
The usual pattern is to have a bootstrap interface that lets the client choose which sub-interface is desired:

```capnp
interface Bootstrap {
  service0 @0 () -> (cap: Service0);
  service1 @1 () -> (cap: Service1);
  service2 @2 () -> (cap: Service2);
}

interface Service0 { ... } 
interface Service1 { ... } 
interface Service2 { ... } 
```

**Comment by 04l3x** [comment]
Sorry, but what exactly does "usually" mean. Does it mean that I have no other way to expose more than one service on the same server than doing promise pipelining? Or does it mean that I can do it but it's complicated to explain and may not be worth doing?

**Comment by dwrensha** [comment]
Can you explain what you don't like about the pattern that I described? Note that [promise pipelining](https://capnproto.org/rpc.html#time-travel-promise-pipelining) means that it does not add any round-trips.

As an alternative, you could instead specify your own little RPC connection initialization protocol, where every connection is expected to send some kind of interface identifier before the actual capnp RPC protocol stream begins. Then the server would only construct the `RpcSystem` object once it receives that identifier and therefore knows which interface to plug in as the bootstrap capability.

**Comment by 04l3x** [comment]
Well, more than don't like it, it's just I want to have both. I don't feel completely comfortable bootstrapping all my services in a external schema language. Honestly I don't completely understand all implications of using all services in only one top level schema or not - I'm just exploring.

I [achieved it](https://gitlab.com/is.not-project/is_not_capnp/-/blob/master/examples/hello-world/src/bin/server.rs) by adding an extra round trip over the socket. I guess if the travel time is not a problem you can use it to host more than capnp's schema in the same server. Also you can still having promise pipelining in the capabilities in what you defined interfaces what uses it.

I wrapped the `capnp::capabilty::Capability` in a `Service` struct adding it an `id`, to then routing the 'Serivce's in a `HashMap`, owned by the `Router` of the  `Server`.

This works with the interface I wanted for the library. But the id generation for each service is coupled between server and client implementation. I don't completely understand how bad is this. Anyway I just want [share](https://crates.io/crates/is-not-capnp) in case anyone wants take a look. I'll still working in this.
