### ISSUE TITLE
Initialize a primitive list from Vec

### ISSUE THREAD

**Issue by erenon** [capnproto/capnproto-rust#419]
I'm looking for an efficient way to initialize a list of primitives. So far I have:

```rust
let input: Vec<f64> = ...;
let nums = my_struct.init_nums(input.len() as u32);
for (i, n) in input.iter().enumerate() {
  nums.set(i as u32, *n);
}
```

This works, but (perhaps because of the bounds checking and casts?) it scales badly with the length of the input (compared to protobuf and a different library). Is there a more direct way to fill a primitive list from a slice of primitives?

Thanks for the great library!

**Comment by dwrensha** [comment]
Setting each element individually is currently the only way to do it.

In principle, we should be able to add a faster and more convenient way, perhaps involving the `SetPointerBuilder` trait:
https://github.com/capnproto/capnproto-rust/blob/7f5b4245fe063472e4b7d5541ebffe06a01ec96b/capnp/src/traits.rs#L82-L88

**Comment by dwrensha** [comment]
Back before the 0.14 release, `SetPointerBuilder` had a type parameter `To`, representing the `Builder` that was getting set: https://github.com/capnproto/capnproto-rust/blob/79a761d10694c3e29c6bdffed50737466436e7ca/capnp/src/traits.rs#L82-L84

Maybe we should bring that parameter back, and make the signature of your `my_struct::Builder::set_nums()` be:

```rust
  fn set_nums<T: SetPointerBuilder<::capnp::primitive_list::Reader<'_,f64>>>(&mut self, value: T) -> ::capnp::Result<()> { ... }
```

There would be an impl of `SetPointerBuilder<::capnp::primitive_list::Reader<'_,f64>` for `&'a[f64]`.

**Comment by dwrensha** [comment]
I started work on this at #421

**Comment by dwrensha** [comment]
@erenon: I found an easy way to boost performance in certain cases: https://github.com/capnproto/capnproto-rust/commit/f4ae39dce25967e919b1bc6f814f8ec9f7942957

For the small test program that I wrote, that diff made things speed up by over 2x.

Can you test whether the diff fixes the performance problems that you noticed? This is a much simpler and less intrusive change than what I was thinking of earlier.

I did try looking at removing bounds checking, but I did not notice any significant performance boost from that.

**Comment by dwrensha** [comment]
Closing, because I believe https://github.com/capnproto/capnproto-rust/commit/f4ae39dce25967e919b1bc6f814f8ec9f7942957 resolves the performance problem. @erenon please re-open, or open a new issue, if your performance problem persists.

**Comment by dwrensha** [comment]
I've revisited the `SetPointerBuilder` approach in #472. That PR now adds support for setting a `primitive_list` field from a native Rust slice.
