### ISSUE TITLE
BufferSegments has the same definition as NoAllocSliceSegments

### ISSUE THREAD

**Issue by ariel-miculas** [capnproto/capnproto-rust#427]
which is: `Segments read from a buffer, useful for when you have the message in a buffer and don’t want the extra copy of read_message.`
This seems to be a copy-paste mistake, but if it's accurate feel free to close this issue.

**Comment by dwrensha** [comment]
Thanks. As park of https://github.com/capnproto/capnproto-rust/commit/4015fa0b44423b867cf632e84408078615aba3eb I removed the extraneous comment.
