### ISSUE TITLE
Implement streaming support

### ISSUE THREAD

**Issue by tamird** [capnproto/capnproto-rust#432]
See https://github.com/capnproto/capnproto/commit/bd6d75ba2515061dfa57ed1badbdf7321bf1fd5f. Presently capnproto-rust uses the fallback and does not natively support streaming. Native support would improve performance.

**Comment by dwrensha** [comment]
Implemented in #517.

**Comment by dwrensha** [comment]
Version 0.20.0 is on crates.io now, with streaming support.
