### ISSUE TITLE
doc: tonic like framework?

### ISSUE THREAD

**Issue by gitmalong** [capnproto/capnproto-rust#438]
Hi!

Is there something like `tonic` for quickly building server / clients?

Thanks

**Comment by dwrensha** [comment]
Did you see the hello-world RPC example? https://github.com/capnproto/capnproto-rust/tree/master/capnp-rpc/examples/hello-world

Can you elaborate on what specific features you are hoping to see?

**Comment by gitmalong** [comment]
Thanks for the link, I wasn't aware of that. That seems to provide similar features as seen in the [tonic hello world tutorial](https://github.com/hyperium/tonic/blob/master/examples/helloworld-tutorial.md) (code generation through build.rs, server impl via trait) which is pretty nice.

Specifically I was looking for a server model that allows me to use tower middleware but there is already an issue for that: https://github.com/capnproto/capnproto-rust/issues/375
