### ISSUE TITLE
Serializing messages with no-alloc

### ISSUE THREAD

**Issue by zer0-droids** [capnproto/capnproto-rust#440]
Hello,

This is more a question than an issue.

I came across this crate recently and discovered that it has a no-alloc feature, which perfectly matches my environment. I've been able to implement a deserialization in my project, as it's done in example/wasm-hello-world/wasm-app/src/lib.rs, but I don't find a way to serialize a message.

Is it implemented for no-alloc? And if yes, would it be possible to have an example of use?

Thanks!

**Comment by dwrensha** [comment]
You'll need to provide your own implementation of the `Allocator` trait:
https://github.com/capnproto/capnproto-rust/blob/20741d11f543d672f3a88d5633652f4af651b0ec/capnp/src/message.rs#L370-L404

One way to do it would be to have a wrapper for a single `&mut[u8]`. That would work simlarly to [`ScratchSpaceHeapAllocator`](https://github.com/capnproto/capnproto-rust/blob/20741d11f543d672f3a88d5633652f4af651b0ec/capnp/src/message.rs#L781-L786), except without the `HeapAllocator` for when the segment fills up. (You would need to panic when the segment fills.)

**Comment by zer0-droids** [comment]
Thank you @dwrensha for the quick reply! I will have a look at this.

**Comment by dwrensha** [comment]
I opened #441, which adds `SingleSegmentAllocator`.

**Comment by zer0-droids** [comment]
Hi @dwrensha,

First, many thanks for the quick new release!

Unfortunately I still have issues to compile in my environment (no-std, no-alloc) something similar as the test case you added. The allocate_zeroed_vec() method returns a Vec<Word> which is not available, but it looks quite easy to fix, by passing to capnp::message::SingleSegmentAllocator::new() a reference to an aligned u8 slice.

The other problem I have seems harder to solve:

`error[E0433]: failed to resolve: could not find `Builder` in `message``

Indeed, the struct Builder<A> is decorated with #[cfg(feature = "alloc")], so it is not available in my environment. We can't simply remove it since it depends on BuilderArenaImpl<A> which uses a Vec.

**Comment by dwrensha** [comment]
Oops!

We need a no-alloc version of `BuilderArenaImpl`. The straightforward way to achieve that would be to hard code it to allow only one segment in the no-alloc case.

**Comment by dwrensha** [comment]
I opened #442.
