### ISSUE TITLE
`connection_state.connection` BorrowMutError

### ISSUE THREAD

**Issue by ImVexed** [capnproto/capnproto-rust#443]
Hello, 

Apologies if this is entirely my fault and not the library, but I've been bashing my head against this for a while and just want a sanity check at this point because I'm not sure I understand how this is happening. 

I have a capability client that can be called from many threads at once inside of my game ECS. So, I wrapped it in a `Arc<Mutex<>>`  and it is referenced like:
```rust
#[derive(Resource)]
pub struct RPCClient {
    match_service: Arc<Mutex<match_service::Client>>,
}

    pub fn place(
        &self,
        commands: &mut Commands,
        session: &Session,
    ) {
        let clone = self.match_service.clone();
        let task = ComputeTaskPool::get().spawn_local(async move {
            let svc = clone.lock().await;

            let mut req = svc.place_request();
            .....
            let reply = req.send().promise.await.unwrap();
            let response = reply.get().unwrap();
            drop(svc);
            println!("response: {:?}", response);
        });
        commands.spawn(PlaceTask(task));
    }
   ```
   
   And I see a panic inside of `capnp-rpc`:
   ```
   thread 'Compute Task Pool (18)' panicked at 'already borrowed: BorrowMutError', /home/co/.cargo/registry/src/index.crates.io-6f17d22bba15001f/capnp-rpc-0.18.0/src/rpc.rs:212:74
stack backtrace:
   0: rust_begin_unwind
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/panicking.rs:67:14
   2: core::result::unwrap_failed
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/result.rs:1651:5
   3: core::result::Result<T,E>::expect
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/result.rs:1033:23
   4: core::cell::RefCell<T>::borrow_mut
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/cell.rs:1017:9
   5: <capnp_rpc::rpc::QuestionRef<VatId> as core::ops::drop::Drop>::drop
             at /home/co/.cargo/registry/src/index.crates.io-6f17d22bba15001f/capnp-rpc-0.18.0/src/rpc.rs:212:41
   6: core::ptr::drop_in_place<capnp_rpc::rpc::QuestionRef<capnp_rpc::rpc_twoparty_capnp::Side>>
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/ptr/mod.rs:497:1
   7: core::ptr::drop_in_place<core::cell::UnsafeCell<capnp_rpc::rpc::QuestionRef<capnp_rpc::rpc_twoparty_capnp::Side>>>
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/ptr/mod.rs:497:1
   8: core::ptr::drop_in_place<core::cell::RefCell<capnp_rpc::rpc::QuestionRef<capnp_rpc::rpc_twoparty_capnp::Side>>>
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/ptr/mod.rs:497:1
   9: <alloc::rc::Rc<T> as core::ops::drop::Drop>::drop
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/alloc/src/rc.rs:1609:17
  10: core::ptr::drop_in_place<alloc::rc::Rc<core::cell::RefCell<capnp_rpc::rpc::QuestionRef<capnp_rpc::rpc_twoparty_capnp::Side>>>>
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/ptr/mod.rs:497:1
  11: core::ptr::drop_in_place<capnp_rpc::rpc::ResponseState<capnp_rpc::rpc_twoparty_capnp::Side>>
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/ptr/mod.rs:497:1
  12: core::ptr::drop_in_place<capnp_rpc::rpc::ResponseVariant<capnp_rpc::rpc_twoparty_capnp::Side>>
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/ptr/mod.rs:497:1
  13: <alloc::rc::Rc<T> as core::ops::drop::Drop>::drop
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/alloc/src/rc.rs:1609:17
  14: core::ptr::drop_in_place<alloc::rc::Rc<capnp_rpc::rpc::ResponseVariant<capnp_rpc::rpc_twoparty_capnp::Side>>>
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/ptr/mod.rs:497:1
  15: core::ptr::drop_in_place<capnp_rpc::rpc::Response<capnp_rpc::rpc_twoparty_capnp::Side>>
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/ptr/mod.rs:497:1
  16: core::ptr::drop_in_place<alloc::boxed::Box<dyn capnp::private::capability::ResponseHook>>
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/ptr/mod.rs:497:1
  17: core::ptr::drop_in_place<capnp::capability::Response<my_bevy_game::rpc::game_capnp::match_service::place_results::Owned>>
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/ptr/mod.rs:497:1
  18:  rpc::client::RPCClient::place::{{closure}}
  ```
  
  I understand that the client is not `send` or `sync` so I figured wrapping it in a mutex would be enough, but it seems to not be the case somehow?
  
  The only other thing I can think of is that I do submit a capability client to the server so that it can callback things to the client. And maybe I'm interacting with `match_service` while the callback is allocating things from a call from the server? But I'm not sure if that's possible either. And I just wanted to post here first to give someone a chance to point out something obvious to me in case I'm missing something.

**Comment by dwrensha** [comment]
The error happens here: https://github.com/capnproto/capnproto-rust/blob/af383af9f42c4310ba7d4698a154ad0da26d6e97/capnp-rpc/src/rpc.rs#L212

I'm a bit confused about how you are managing to call the `match::Client` from multiple threads. Is your `RPCClient` struct `Send` somehow? Does `ComputeTaskPool::spawn_local()` push its task to other threads (despite the "local" in its name)?

**Comment by ImVexed** [comment]
It shouldn't be, as it specifically notes: `Users should generally prefer to use TaskPool::spawn instead, unless the provided future is not Send.`

I did mark RPCClient itself as send like `unsafe impl Send for RPCClient {}` to get it to play nice with ECS it's being inserted into knowing it would be accessed from many threads. But had made the now obviously wrong assumption that `Arc<Mutex<>>` would prevent any issues there by enforcing a single owner of the client at any moment. 

Is there a safe way to guard `send` access to a `!send` resource then? Or should I just throw access behind a tx/rx queue?

**Comment by dwrensha** [comment]
> Or should I just throw access behind a tx/rx queue?

That's what I've always done when I've needed to get capnp-rpc working in a multithreaded context. The downside is that it does tend to add a lot of boilerplate logic to pass around all the needed messages.

Some related previous discussion:
https://github.com/capnproto/capnproto-rust/issues/180
https://github.com/capnproto/capnproto-rust/issues/271#issuecomment-1146944845

**Comment by ImVexed** [comment]
Yeah I threw it behind a queue and it's not panicing anymore, thanks!
