### ISSUE TITLE
Backport capnp-futures changes from master to 0.14 version

### ISSUE THREAD

**Issue by paulnice** [capnproto/capnproto-rust#448]
capnp-futures recently got fixes for a critical issue: https://github.com/capnproto/capnproto-rust/commit/161b8482f2517c73cdb998f5a6ce6150f6229240

These fixes should be backported to all current versions of capnp-futures: 0.14, 0.15, 0.16, 0.17, 0.18

**Comment by dwrensha** [comment]
Done, with packages pushed to crates.io for 0.14, 0.15, 0.16, 0.17, and 0.18.

**Comment by paulnice** [comment]
@dwrensha David, thank you very much for your prompt help! I really appreciate it!
