### ISSUE TITLE
Serializing message to &[u8]

### ISSUE THREAD

**Issue by kolegs** [capnproto/capnproto-rust#454]
Hi @dwrensha,

So I've been testing `serialize::write_message` function the other day. I used a simple [u8] as a buffer and my question is what is the best way to know how many bytes were written to the buffer? By going through the code I figured out that you can simply loop through segments and sum the size, and at the end add `8` for a table size.
But this looks kind of inefficient.

If there is no other way, what do you think about returning number of bytes written from the function itself? 
Right now it is returning `Result<(), Error>`. If you are fine with the idea I can implement that since that would simplify my code anyway :)

**Comment by dwrensha** [comment]
If `x : &mut [u8]` and you pass `x` to `serialize::write_message()`, after the call completes, `x` will have advanced to the remainder of the buffer. So you could compute the number of bytes written by taking the difference of `x.as_ptr()` before and after the call.

**Comment by kolegs** [comment]
Thanks, works. Reference for the future:
```
            let mut serialize_buffer = [0u8; 256];
            let mut x: &mut [u8] = &mut serialize_buffer;
            let result = serialize::write_message(&mut x, &message);
            assert!(result.is_ok());
            assert_eq!(x.as_ptr() as usize - serialize_buffer.as_ptr() as usize, expected_buffer_size);
```
