### ISSUE TITLE
From bytes to TypedReader

### ISSUE THREAD

**Issue by kolegs** [capnproto/capnproto-rust#483]
Hi,

I am trying to implement a helper function that allows to create `TypedReader` from bytes. I've came up with something like that:

```
pub fn from_bytes2<S: Owned, const N: usize>(
    data: &[u8],
) -> Result<TypedReader<capnp::message::Builder<SingleSegmentAllocator<[u8; N]>>, S>, Error> {
    let mut buffer = [0u8; N];
    let message_reader = capnp::serialize::read_message_no_alloc(
        data,
        &mut buffer,
        capnp::message::ReaderOptions::new(),
    );

    if message_reader.is_err() {
        return Err(Error); // TODO: error handling
    }

    let message_reader = message_reader.unwrap();

    let allocator = SingleSegmentAllocator::new([0u8; N]);
    let mut message = Builder::new(allocator);
    let root = message_reader.get_root::<S::Reader<'_>>();
    if root.is_err() {
        return Err(Error); // TODO: error handling
    }
    let result = message.set_root(root.unwrap());
    if result.is_err() {
        return Err(Error); // TODO: error handling
    }

    Ok(TypedReader::new(message.into_reader()))
}
```

But when I test it I am getting an error:
```
            let typed_reader =
                super::from_bytes2::<test_capnp::test_data::Owned, MSG_SIZE>(&data);

            let mut typed_reader = typed_reader.unwrap();

            let reader = typed_reader.get().unwrap();   // < -- This crashes with Error MessageContainsNonStructPointerWhereStructPointerWasExpected
```

I was able to create a similar function that uses `TypedBuilder` instead of `TypedReader` but I would prefer to use `TypedReader` at the end. Is it possible? Hints would be appriciated
Oh, I use `no-alloc`, `no-std` version

**Comment by dwrensha** [comment]
That should work. How are you initially creating the encoded message? 

> I was able to create a similar function that uses `TypedBuilder` instead of `TypedReader` 

Can you show me what that code looks like? If that works, then I expect the `TypedReader` version to work too.

---

As an aside: it would be nice if you did not need to go through a `message::Builder` at all for this. My hope was that `serialize::read_message_no_alloc()` would be sufficient, but I suppose that it can be inconvenient to use, because the returned `message::Reader` has its lifetime tied to the borrow of `&mut buffer`.

So maybe we need something more like this:
```rust
pub fn read_message_no_alloc<R, B>(
    mut read: R,
    buffer: B,
    options: message::ReaderOptions,
) -> Result<message::Reader<NoAllocBufferSegments<B>>>
where
    R: Read,
    B : AsMut<[u8]>, AsRef<[u8]>
{
  ...
}
```
and then you could pass in a `[u8; N]` and not need to worry about lifetimes.

**Comment by dwrensha** [comment]
I am able to replicate similar behavior locally. Investigating...

**Comment by dwrensha** [comment]
The problem is that the `segment` field in `SingleSegmentAllocator` can move, and therefore invalidate the pointer held by `arena::BuilderSegmentArray`. :facepalm: 
https://github.com/capnproto/capnproto-rust/blob/3180a44b58440424cb420fe8464ab5bd0fb1864e/capnp/src/message.rs#L905-L908

**Comment by dwrensha** [comment]
#484 should remove the unsoundness. Unfortunately, it also makes it harder for downstream code like yours to deal with lifetimes.

**Comment by dwrensha** [comment]
Thanks for the report!
