### ISSUE TITLE
Kudos to builders of this Rust library - Every single one of you.

### ISSUE THREAD

**Issue by vertexclique** [capnproto/capnproto-rust#490]
After the hell of a embedding executors into the libraries and calling it off by Rust community. You are the last stand who proves that there are sane people around the world. Much thanks, SANS IO rocks. Carry on!
Whomever properly builds software with sanity, must be getting appreciation from my pov!

**Comment by dwrensha** [comment]
Thanks -- that's good to hear! Usually I only hear negative feedback.

I would be curious to hear more about your use case, if you are willing to share. It sounds like you're mainly interested in the [base serialization crate](https://crates.io/crates/capnp), and that the [ability to disable the `std` feature](https://github.com/capnproto/capnproto-rust/blob/528b64b8ca2faca2639294b776b5703c5bb1c5e3/capnp/Cargo.toml#L35-L37) is important to you? Do you have any need for async I/O?

**Comment by vertexclique** [comment]
I am interested in base serialization with async IO support, yes. I skim through the code swiftly to understand how did you design async IO operation and I liked it. Wanted to state that for all. I will be using this hopefully in various projects of mine.

**Comment by dwrensha** [comment]
Closing this because it's not an actionable issue. https://github.com/capnproto/capnproto-rust/discussions is the place for more open-ended discussions.
