### ISSUE TITLE
[Question]How to extract generic type values

### ISSUE THREAD

**Issue by SteveLauC** [capnproto/capnproto-rust#491]
Hi! Thanks for this amazing project!

I would like to know how I can extract the value of a generic type from its `Reader` type.

For example, for the following `Entry` type:

```
struct Entry(K, V) {
  key @0 :K;
  value @1 :V;
}
```

I want to implement `From<entry::Reader<'_, K, V> for (K, V)`:

```rs
impl<K, V> From<entry::Reader<'_, K, V>> for (K, V)
where
    K: capnp::traits::Owned,
    V: capnp::traits::Owned,
{
    fn from(value: crate::map_capnp::entry::Reader<'_, K, V>) -> Self {
        let key: <K as Owned>::Reader = value.get_key().unwrap();
        let value: <V as Owned>::Reader = value.get_value().unwrap();

        
        todo!()
    }
}
```

As you can see, I can access their `Reader` types, but how can I extra their values, i.e., values of type `K` and `V`, thanks!

**Comment by dwrensha** [comment]
There are no useful values of types `K` and `V`. The only way to interact with Cap'n Proto data is through `Reader` and `Builder` types. See this comment: https://github.com/capnproto/capnproto-rust/blob/528b64b8ca2faca2639294b776b5703c5bb1c5e3/capnp/src/traits.rs#L51-L64.

**Comment by SteveLauC** [comment]
```rs
impl<K, V> From<entry::Reader<'_, K, V>> for (K, V)
where
    K: capnp::traits::Owned,
    V: capnp::traits::Owned,
{
    fn from(value: crate::map_capnp::entry::Reader<'_, K, V>) -> Self {
        let key: <K as Owned>::Reader = value.get_key().unwrap();
        let value: <V as Owned>::Reader = value.get_value().unwrap();

        
        todo!()
    }
}
```

Thanks for the quick response, so if I understand correctly, the generic types `K` and `V` defined in the above code are CapN types, I cannot convert `Entry` to a CapN `(K, V)` pair, instead, I should define 2 extra Rust `K` `V` types:


```rs
impl <CapnK, CapnV, RustK, RustV> From<Entry<'_, CapnK, CapnV>> for (RustK, RustV) 
```

and there should be a trait bound that one can convert a `<CapnK as Owned>::Reader` to a `RustK`, something like:

```rs
where RustK: From<<CapnK as Owned>::Reader>

**Comment by SteveLauC** [comment]
Hi, I am curious if the approach presented in my last comment is feasible, it seems there is no general abstraction (traits or methods) to extract the `RustK` value from the `CapnK` reader type, I have to know the concrete reader type (`struct_list::Reader`, `dynamic_value::Reader`, etc) and call the corresponding methods to get the value.

**Comment by dwrensha** [comment]
> the generic types K and V defined in the above code are CapN types

Correct. Generic type in Cap'n Proto messages can only be instantiated with Cap'n Proto types.

> it seems there is no general abstraction (traits or methods) to extract the RustK value from the CapnK reader type

That's correct. In https://github.com/capnproto/capnproto-rust/pull/157 there was some work towards proc macros that convert between capnproto and rust-native types. That got turned into its own repo (which I have not looked at in depth): https://github.com/aikalant/capnp_conv

**Comment by SteveLauC** [comment]
> That's correct. In https://github.com/capnproto/capnproto-rust/pull/157 there was some work towards proc macros that convert between capnproto and rust-native types. That got turned into its own repo (which I have not looked at in depth): https://github.com/aikalant/capnp_conv

Yeah, that crate defines 2 helper traits like:

```rs
pub trait Writable {
    type OwnedType: capnp::traits::Owned;

    fn write(&self, builder: <Self::OwnedType as Owned>::Builder<'_>);
}

pub trait Readable
where
    Self: Sized,
{
    type OwnedType: capnp::traits::Owned;

    fn read(reader: <Self::OwnedType as Owned>::Reader<'_>) -> Result<Self>;
}
```

so that one can do `<RustK as Readable>::read(CapnK_reader)` to extract the value, though I didn't take a deep look either.


Thanks for the response!
