### ISSUE TITLE
capnp_rpc does not work on monoio

### ISSUE THREAD

**Issue by SteveLauC** [capnproto/capnproto-rust#495]
Hi:)

I am playing the `hello-world` example on [monoio](https://github.com/bytedance/monoio) (A runtime that is based on io_uring), but both server and client sides block, and from my observation, `.await`ing `RpcSystem` won't finish and simply blocks, so I come here to seek some help:>

You can find the code [here](https://github.com/SteveLauC/capnp_rpc_monoio), in README, I documented the [changes that I have made to the original code](https://github.com/SteveLauC/capnp_rpc_monoio?tab=readme-ov-file#changes-made-to-the-original-code) and [some observations that I found while debugging the program](https://github.com/SteveLauC/capnp_rpc_monoio?tab=readme-ov-file#things-i-observed-both-server-and-client-side), hope they will help a bit.

**Comment by dwrensha** [comment]
Interesting. What happens if you try a simpler example that uses only [capnp-futures](https://github.com/capnproto/capnproto-rust/tree/master/capnp-futures) (and no RPC)? Does that hit a similar problem?

**Comment by SteveLauC** [comment]
Hi! Thanks for your help and response!

I wrote a single TCP server that would echo the message received from client (pretty similar to the capnp-rpc hello-world example) using capnp-futures and monoio ([repo](https://github.com/SteveLauC/capnp_futures_monoio)), and it look like it is working pretty well:

```sh
$ cargo b
$ ./target/debug/capnp_futures_monoio server 127.0.0.1:8100
INFO: server listening on 127.0.0.1:8100
```
```sh
$ ./target/debug/capnp_futures_monoio client 127.0.0.1:8100 hello
```
```sh
$ ./target/debug/capnp_futures_monoio server 127.0.0.1:8100
INFO: server listening on 127.0.0.1:8100
INFO: Server received hello
```

**Comment by SteveLauC** [comment]
Well, it turns out that it WORKS on monoio!

It blocks in my repo because I .awaited the `RpcSystem`, which should not be done, so this issue does not exist, closing.

**Comment by dwrensha** [comment]
Ah, right. The `RpcSystem` needs to be driven, but if you `await` it in the main task then it will never finish. You need to spawn a new task for it.
