### ISSUE TITLE
traits.ListIter incorrectly implementing ExactSizeIterator

### ISSUE THREAD

**Issue by nairb774** [capnproto/capnproto-rust#504]
The documentation for ExactSizeIterator.len() states:
> Returns the exact remaining length of the iterator.

https://docs.rs/capnp/0.19.5/capnp/traits/struct.ListIter.html#impl-ExactSizeIterator-for-ListIter%3CT,+U%3E

It looks like the implementation returns the total length of the iterator not the length remaining.

**Comment by dwrensha** [comment]
Good catch! #505 fixes this.
