### ISSUE TITLE
doc: read_message_from_flat_slice_no_alloc docstring bad autocomplete

### ISSUE THREAD

**Issue by tv42** [capnproto/capnproto-rust#508]
I believe the read_message_from_flat_slice_no_alloc docstring contains an incorrect autocomplete that went unnoticed.

https://github.com/capnproto/capnproto-rust/blob/3d4b78d5d17fcd851c32d38123dac51f34fca498/capnp/src/serialize.rs#L83

It seems it meant to say 

> Unlike read_message_from_flat_slice it does not do heap allocation

**Comment by dwrensha** [comment]
Good catch! Fixed in https://github.com/capnproto/capnproto-rust/commit/d0e10368a023deaa33b9190c2017708f8088222d.
