### ISSUE TITLE
Making rust capn proto fully async

### ISSUE THREAD

**Issue by AbdulWMughal** [capnproto/capnproto-rust#510]
Are the team for this crate planning on making it fully asynchronous as i believe it’s synchronous right now?

**Comment by dwrensha** [comment]
Did you see the [capnp_futures](https://docs.rs/capnp-futures/latest/capnp_futures/) crate?

**Comment by dwrensha** [comment]
Closing because the `capnp_futures` crate already exists and it supports async reading and writing of Cap'n Proto messages.
