### ISSUE TITLE
Serializing from borrowed TypedReader

### ISSUE THREAD

**Issue by marmeladema** [capnproto/capnproto-rust#524]
Hello,

I happen to face a situation where in some API I have a borrowed TypedReader and I need to serialize it.

I might have missed something, but it seems to serialize from a reader, I need access to the ReaderSegments which I can only obtain by doing typed_reader.into_inner().into_segments() which is consuming the input TypedReader.
However the serializing functions (the _to_words ones) actually accept a borrowed ReaderSegments.

Is there a reason for not exposing a borrowed ReaderSegments?
If we added a method like `get_reader_segments(&self) -> &S` it should fix my issue.

Thank you for your help.

**Comment by dwrensha** [comment]
Adding a `message::Reader::get_segments()` method makes sense to me.

**Comment by marmeladema** [comment]
Okay I'll try to open a PR soon :-)
