### ISSUE TITLE
[Question]: Order of requests in capnp-rpc

### ISSUE THREAD

**Issue by SteveLauC** [capnproto/capnproto-rust#528]
Hi, thanks for the work on the project!

I would like to know the answers to the following questions:

1. With only 1 connection between client and server, does capnp-rpc preserve the order in which requests are sent? i.e., the first request will be handled first.
2. With only 1 connection between client and server, if multiple requests of the **same RPC interface** arrive in order, will they be handled sequentially? If these requests belong to **different RPC interfaces**, will they be handled sequentially as well? I guess the answer to both questions is yes because capnp-rpc is runtime-agnostic and does not "spawn()" things

**Comment by dwrensha** [comment]
> 1. With only 1 connection between client and server, does capnp-rpc preserve the order in which requests are sent? 

capnp-rpc is supposed to deliver messages in the order they were received: https://github.com/capnproto/capnproto/discussions/1862#discussioncomment-7738684

However, there are some known issues. For example, promise resolution over a two-hop connection could break ordering (#529). Moreover, we currently depend on the task scheduler (tokio usually) being first-in-first-out: https://github.com/capnproto/capnproto-rust/blob/0c5996a44cef49ae233b7ce0f9d5479864afaf96/capnp-rpc/src/local.rs#L414-L421

> 2. With only 1 connection between client and server, if multiple requests of the same RPC interface arrive in order, will they be handled sequentially? 

Method calls are initiated sequentially (each call gets access to  `&mut self`, so this must be the case). If a call returns a future constructed with `Promise::from_future()`, then the remaining action represented by that future can take place concurrently (interleaved) with other calls. For example, if a method body returns `Promise::from_future(future::pending())` then the call never terminates (the client never gets a response), but other calls can still take place unobstructed.

**Comment by dwrensha** [comment]
Closing because this is a question not an issue. In the future, please use https://github.com/capnproto/capnproto-rust/discussions for this kind of thing.

**Comment by SteveLauC** [comment]
Thanks for answering the question!

>  In the future, please use https://github.com/capnproto/capnproto-rust/discussions for this kind of thing.

Sorry for using issue for questions 😵, I will use discussion next time.
