### ISSUE TITLE
Fails to build with capnp 0.6.x

### ISSUE THREAD

**Issue by drahnr** [capnproto/capnproto-rust#73]

**Comment by dwrensha** [comment]
Hm. It should work, and it has worked for me so far.

What specific error are you seeing? What versions are you using? What operating system? What source code / schemas are you trying to compile?

**Comment by drahnr** [comment]
I am on Fedora 26 x86_64, the error is rather unspecific saying the [build.rs](https://github.com/spearow/juice/blob/master/build.rs) fails.

I have yet to dive into the details of it.

**Comment by drahnr** [comment]
```
# ls -al /usr/bin/capnp*
-rwxr-xr-x. 1 root root 216416 Jun  9 18:38 /usr/bin/capnp
lrwxrwxrwx. 1 root root      5 Jun  9 18:37 /usr/bin/capnpc -> capnp
-rwxr-xr-x. 1 root root 551096 Jun  9 18:38 /usr/bin/capnpc-c++
-rwxr-xr-x. 1 root root 135600 Jun  9 18:38 /usr/bin/capnpc-capnp
```

```
# capnp --version
Cap'n Proto version (unknown)
```

```
error: failed to run custom build command for `juice v0.2.2 (file:///home/bernhard/Projects/spearow/juice)`
process didn't exit successfully: `/home/bernhard/Projects/spearow/juice/target/debug/build/juice-261dc55af35add6f/build-script-build` (signal: 11, SIGSEGV: invalid memory reference)

```

**Comment by drahnr** [comment]
Is it necessary to also do a `cargo install capnp`?

EIther that or a rustup of the toolchain did the trick

**Comment by dwrensha** [comment]
`cargo install` should not make a difference.

I'm not sure how `rustup` would help. Do you happen to know which versions of `rustc` and `cargo `you were using before you updated?

Did you also upgrade the fedora package?

**Comment by drahnr** [comment]
I did not upgrade any fedora packages and I am not aware of the previous rust toolchain I used unfortunately, I am on nightly though so that might have been a reason.

**Comment by drahnr** [comment]
I think you can safely close this... I will re-open if needed.
