### ISSUE TITLE
If layout allows provide a slice view into primitive list

### ISSUE THREAD

**Issue by mmacedoeu** [capnproto/capnproto-rust#76]
As I could see to get a memory aligned [u64] in capnproto you must use a primitive list with T = u64/UInt64 but them it is unclear how to get access to a slice of it

**Comment by dwrensha** [comment]
Correct, there is currently no way to get a slice into the data, for a couple of reasons:

  1. Endianness. The data will always be encoded in little-endian order, but the library needs to also work on big-endian systems. I suppose maybe we could conditionally omit the hypothetical `to_slice()` function on big-endian systems?
  2. List upgrades (discussed [here](https://groups.google.com/forum/#!msg/capnproto/lRlWBOglQv4/BObDVrTcwisJ)). Primitive lists are permitted to be upgraded to struct lists, so `primitive_list::Reader` needs to be able to deal with cases where the elements are not tightly packed. I suppose a hypothetical `to_slice()` function could return an error if the elements are tightly packed?

**Comment by dwrensha** [comment]
See related discussion on #97.

**Comment by dwrensha** [comment]
`capnp::raw::get_list_bytes()` was added in 6683d7accc8199f94e5d7b5a75b4740f4478f624
