### ISSUE TITLE
get_foo() fails for empty strings in LTO builds only

### ISSUE THREAD

**Issue by FauxFaux** [capnproto/capnproto-rust#81]
I have a `without @1 :Text;` field in a message which is (intentionally) *not* initialised. The result of calling `get_without()` on the reader for this message varies based on compile settings. This is not ideal.

With `--release` and `lto = true`, it returns an error:

> Error { kind: Failed, description: "Message contains non-list pointer where text was expected." }

On all other configurations, including `--release` without `lto = true`, and non-release, it returns the empty string.

This is, um, not expected.

 * Is there any intentional variation in `capnproto-rust`, or is this arguably a compiler bug?
 * What's the expected output? Should `get_` error for missing fields?
 * What does the error mean?

---

I've made a [sample project](https://github.com/FauxFaux/capnp-get-null), which will demonstrate the problem with `cargo run --release`. The other cases can be tested with `cargo run` and by `#commenting` `lto = true` in `Cargo.toml`, and `cargo run --release`. It's a binary (which does nothing on success) as it doesn't seem to fail in `cargo test --release`; didn't look why.

```bash
git clone https://github.com/FauxFaux/capnp-get-null
cd capnp-get-null
RUST_BACKTRACE=1 cargo run --release
```
```
    Finished release [optimized + debuginfo] target(s) in 0.0 secs
     Running `target/release/capnp-get-null`
thread 'main' panicked at 'without: Error { kind: Failed, description: "Message contains non-list pointer where text was expected." }', /checkout/src/libcore/result.rs:906:4
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
...
   6: core::result::unwrap_failed
             at /checkout/src/libcore/macros.rs:41
   7: capnp_get_null::main
             at /checkout/src/libcore/result.rs:799
             at src/main.rs:28
             at src/main.rs:35
   8: main
   9: __libc_start_main
  10: _start
```

The code which errors is at: [main.rs:28](https://github.com/FauxFaux/capnp-get-null/blob/ec7dd6ca9a090d1516c29984c3e685b5343f25a7/src/main.rs#L28)

The schema is totally trivial:
```capnp
@0xbc035dbe0d877227;

struct Foo {
    with    @0 :Text;
    without @1 :Text;
}
```

Tested on Ubuntu 17.10 (Artful) amd64 with `rustc 1.21.0 (3b72af97e 2017-10-09)` (stable) and `rustc 1.23.0-nightly (8b22e70b2 2017-10-31)`.

**Comment by dwrensha** [comment]
Wow! Thanks for the detailed report.

I believe this is fixed by https://github.com/capnproto/capnproto-rust/commit/7479b4e3f666187d17ea0fbba4717ea6bf3cee60. New release coming shortly.

**Comment by dwrensha** [comment]
Ah, indeed, the documentation of `slice::from_raw_parts()` discusses this: https://doc.rust-lang.org/std/slice/fn.from_raw_parts.html

> p must be non-null, even for zero-length slices, because non-zero bits are required to distinguish
> between a zero-length slice within Some() from None. p can be a bogus non-dereferencable pointer,
> such as 0x1, for zero-length slices, though.
