### ISSUE TITLE
Null handling

### ISSUE THREAD

**Issue by griff** [capnproto/capnproto-rust#94]
I don't know if this is the right place to ask this question but I was curious about why you chose to have a has_* method for null check instead of just returning an Option from get_*?

**Comment by dwrensha** [comment]
If `has_foo()` returns false (on a non-union field), you can still call `get_foo()` and get a default value. Automatically providing defaults in this way is often more convenient for the user, who would otherwise need to supply them after detecting a `None`.

**Comment by griff** [comment]
I am just spitballing here but could an implementation of `Default` by the Readers and `unwrap_or_default` serve the same purpose of getting the default value?

**Comment by dwrensha** [comment]
Yeah, I think that could work. Another constraint to keep in mind is that it's nice to have the `Builder` interface mirror the `Reader` interface, and for builders the default value needs to be a mutable reference into the message, so probably can't be provided by the `Default` trait.

**Comment by dwrensha** [comment]
Closing because this is more of a question than an actionable bug.

**Comment by ozgrakkurt** [comment]
@dwrensha this does cause some issues FWIIW, in some contexts the default value for the things isn't really a valid value like doing a zeroed version of a struct if it is unitialized etc.
