### ISSUE TITLE
Any plans on making RpcSystem "Send" ?

### ISSUE THREAD

**Issue by Globidev** [capnproto/capnproto-rust#96]
I noticed that the examples are still using tokio pre 0.1 (tokio-core)

I wanted to use capnp-rpc with tokio 0.1 but it is hardly usable because the default executor is now threadpooled and functions like `spawn` and `run` require futures to be `Send`. Note that there is a new `Executor` trait that is part of tokio which also requires futures to be `Send`.

`RpcSystem` is not `Send` because it contains some `Rc`s: one through its `connection_state` field and the other indirectly through `TaskSet`'s `reaper` field.

Are there any plans on making the rpc crate thread pool friendly ?

**Comment by dwrensha** [comment]
Does tokio's current thread executor work for you?
https://docs.rs/tokio/0.1.7/tokio/executor/current_thread/index.html

**Comment by zacheryph** [comment]
`current_thread` does work in some play code that I have worked on. Although I read today on gitter that `current_thread` is going to be `doc(hidden)` and deprecated on the next release.

Play Code: https://gitlab.com/zacheryph/examples/tree/master/rust/capnp-fun

This _could_ be reasonable in an application and spawn a dedicated thread to only capnp although with it being deprecated (and eventually removed) id say something else has to happen.

**Comment by carllerche** [comment]
`tokio::executor::current_thread` was deprecated, but that is just the module location.

`tokio::runtime::current_thread` is the preferred strategy.

**Comment by Globidev** [comment]
I indeed ended up using the `current_thread` runtime.
Had some issues with timers inside rpc calls because they are not spawned on that runtime's executor by default but instantiating a `current_thread::Runtime` manually before doing everything else solved my problems.

I was still mainly curious about whether or not there were plans on supporting multi-threaded executors

**Comment by dwrensha** [comment]
> I was still mainly curious about whether or not there were plans on supporting multi-threaded executors

I have no current such plans. If you have cpu-intensive work, I expect that you should be able to offload it to a threadpool, even if your RPC objects themselves must live on a single thread.

It would be interesting to experiment with more of a multithreaded approach in the RPC system implementation. I haven't made any serious attempts at it because:
  1. I expect it would make the implementation significantly more complicated
  2. I actually usually want my RPC objects to be non-`Send`, so that can share data with each other without needing to synchronize.

**Comment by Globidev** [comment]
I see, thanks for clarifying 👍

**Comment by izolyomi** [comment]
Concerning the recent directions of Rust, Tokio is usable quite limitedly without the futures being `Send` (it's a common requirement in many crates) and the upcoming async/await feature seems to make `Send` mandatory.

With these highlights, are you sure you will not revisit this decision? It will likely make the current implementation obsolete to the point where we'll be forced to drop Capnp just because of this.

**Comment by dwrensha** [comment]
> the upcoming async/await feature seems to make `Send` mandatory

I would be alarmed if that were the case. Could you link to any documentation or discussion that gave you that impression?

**Comment by izolyomi** [comment]
I gave it a shot and tried to come up with a minimal reproducible example with clean `async/await` code. Sorry that it's not closely related to capnp, but it'd have made the whole picture much more complicated.

Seems that things might work while using `async` purely without ever writing a `Future` type. The moment you have futures on your API (and this is the case with capnp `Promise`), the problems appear. Consider the following (tried with the latest nightly 1.36):

`Cargo.toml`

```
[package]
name = "async-send"
version = "0.1.0"
edition = "2018"

[dependencies]
tokio = {version = "*", features = ["async-await-preview"]}
tokio-async-await = "*"
```

`src/main.rs`

```rust
#![feature(await_macro, async_await)]

use std::future::Future;
use std::rc::Rc;
use std::time::{Duration, Instant};
use tokio::prelude::Future as OldFuture;
use tokio::timer::Delay;
use tokio_async_await::compat::forward::IntoAwaitable;

fn sample() -> impl Future<Output=Result<Rc<String>,()>> {
    let deadline = Instant::now().checked_add(Duration::from_secs(5)).unwrap();
    let fut = Delay::new(deadline)
        .then(|result| result
            .map(|()| "works").or(Ok("failed"))
            .map(|s| Rc::new(s.to_string())) );
    Box::new(fut.into_awaitable() )
}

fn main() {
    tokio::run_async(async {
        let answer = await!(sample());
        println!("Answer: {:?}", answer);
    } );
}
```

This uses a single timeout as one of the simplest features of Tokio. It works with a `String` but fails to compile at the moment of adding the `Rc` as a non-`Send` return type. (The `Result` is only needed for the conversion between old and new-style futures)

Note I might have a limited understanding of the problem space and workarounds for this. If so, please advise what I should do differently.

**Comment by zacheryph** [comment]
I don't know for sure, but I doubt `async/await` really cares about `Send` what so ever. Whatever you are using to drive your Futures is what cares about this.

David specified reasons above for not wanting `Send`. Also as stated previously, if you use the `tokio::runtime::current_thread` runtime there is no reason / dependency for `Send`. Now getting that runtime to accept `std::future::Future` if it doesn't already is an entirely different issue and unrelated to this library.

**Comment by Perksey** [comment]
Just ran into a need for this. Trying to use capnp-rpc as a communication mechanism for a WASM plugin system, where the FFI defined functions for "bridging" an asynchronous runtime held by the host i.e. the plugin has the ability to spawn and wake futures on the host, which are then polled on the plugin.

Using a current thread executor was a not deemed to be an acceptable solution for this use case as this would require that each plugin have its own dedicated thread on the host.
